# Hebrew Law Corpus → LLooM v2.1: semantic diagnostics + condition-faithful labels

This is the **v2.1** experiment runner. It reuses the passed-laws corpus and the
same shared preparation pipeline as the baseline (`lawsofisrael.extraction` +
`lawsofisrael.chunking`), but restructures the concept-discovery flow so that
**semantic diagnostics come before any density clustering**:

1. **Custom, context-rich summaries.** LLooM's generic default summary is
   replaced by a versioned free-form Hebrew prompt (`prompts_v2`) that keeps the
   details distinguishing one operative rule from another (affected population,
   actor, legal action, object, domain, exception/condition/timeframe) instead
   of collapsing to generic verbs like *תיקון חוק* or *הארכת תוקף*. The default
   quote filter is unchanged.
2. **Pre-clustering bullet artifact.** The exact bullets entering the embedding
   stage are captured with stable ids, chunk linkage, and honest accounting of
   how many chunks produced no bullet.
3. **Nearest-neighbor explorer.** The bullets are embedded with the local
   bge-m3 model and their cosine nearest neighbors are inspected **before** any
   UMAP/HDBSCAN, so we can judge whether legally similar provisions are close in
   the raw embedding space.
4. **Reproducible clustering diagnostics.** A seeded UMAP+HDBSCAN wrapper
   (`diagnostics_v2.ClusterConfig`) retains embeddings, coordinates, the fitted
   estimator, labels, membership probabilities, and outlier scores, plus the
   condensed-tree table/plot — **no cluster-size cutoff is baked in**.
5. **Deliberate selection → synthesis.** Only after inspecting diagnostics do we
   *manually* choose one clustering configuration; labels are synthesized from
   that result with the condition-faithful synthesis prompt.

**No scoring / no apply.** There is no `session.score`, no `scores_df`, no
`scores.parquet`. **Caveat:** a cluster label is a *shared legal pattern*, not
shared legislative intent (see the embedded caveat).

## 0. Setup

In [2]:
# Auto-reload edited package modules so changes to `lawsofisrael` are picked
# up without restarting the kernel (avoids stale-import AttributeErrors).
%load_ext autoreload
%autoreload 2

from pathlib import Path
from datetime import datetime, timezone
from importlib.metadata import version
import json
import sys

import pandas as pd

In [3]:
# NOTE: if you started this kernel before updating the lawsofisrael package,
# restart the kernel once (Kernel -> Restart) so the latest module is loaded.

ROOT = Path.cwd().resolve().parent
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / 'src'))

from config import (
    MODEL_CONFIG, EMBEDDING_URL, EMBEDDING_MODEL, EMBEDDING_API_KEY,
    MAX_CONTEXT_TOKENS, MAX_OUTPUT_TOKENS,
    GEMINI_EMBEDDING_MODEL, GEMINI_EMBEDDING_DIM,
    GEMINI_EMBEDDING_BASE_URL, GEMINI_EMBEDDING_API_KEY,
)
from lawsofisrael import extraction, chunking, prompts_v2, v2_export
from lawsofisrael import diagnostics_v2 as diag
from lawsofisrael.lloom import make_lloom_session, build_gemini_embed_model

CACHE = ROOT / 'notebooks' / 'cache'
EXTRACTION_CACHE = CACHE / 'extraction'
OUTPUTS = ROOT / 'notebooks' / 'outputs'
DIAG_DIR = OUTPUTS / 'diagnostics'

CHAT_MODEL = MODEL_CONFIG['name']
CHAT_API_KEY = MODEL_CONFIG['api_key']
CHAT_BASE_URL = MODEL_CONFIG['base_url']
EMBED_URL = EMBEDDING_URL
EMBED_MODEL = EMBEDDING_MODEL
EMBED_API_KEY = EMBEDDING_API_KEY

CHUNK_TOKENS = chunking.compute_chunk_budget(MAX_CONTEXT_TOKENS, MAX_OUTPUT_TOKENS)

CORPUS_ID = 'nickbes/lawsofisrael'

# Corpus size. Density clustering needs enough bullets from enough distinct
# legal domains to have real similarity contrast; a handful of bills produces
# only same-bill neighbors and no usable clusters. The dataset has ~600 bills.
# Use a substantial subset here (fast enough to iterate, large enough for the
# diagnostics to be meaningful); set N_BILLS = None to run over ALL ~600 bills.
N_BILLS = 100

# Generation parameters (kept comparable to the v1 baseline).
GEN_PARAMS = {'filter_n_quotes': 5, 'summ_n_bullets': 7, 'synth_n_concepts': 3}
MAX_CONCEPTS = 30

# Nearest-neighbor explorer: how many neighbors to show per bullet.
NN_K = 5

# --- Embedding representation controls (diagnostics only) -------------------
# EMBED_BACKEND: 'gemini' = the API gemini-embedding model via the same
# OpenAI-compatible provider as the chat model (SENDS bullet text to the API);
# 'local' = local bge-m3 (session.cluster_model, no data leaves the machine).
# Default is 'gemini' for the current representation experiment; switch to
# 'local' if you must keep bullet text off the third-party API.
EMBED_BACKEND = 'gemini'
# Option 1: task instruction prefix. None = embed the bare bullet.
EMBED_INSTRUCTION = diag.DEFAULT_EMBED_INSTRUCTION
# Option 2: enrich each bullet with its chunk's domain (bill title + heading).
USE_DOMAIN_CONTEXT = True

## 1. Verify servers

In [4]:
import requests
from openai import OpenAI

if not CHAT_API_KEY:
    print("✗ OPENAI_API_KEY is not set. Copy .env.example to .env and fill it in.")

# The local bge-m3 server is only needed when the diagnostics embed locally.
# (LLooM's built-in clustering is NOT used in the v2.1 split flow, so the
# session's local cluster_model is never exercised for clustering.)
if EMBED_BACKEND == 'local':
    try:
        requests.get(f"{EMBED_URL}/health", timeout=5).raise_for_status()
        print("✓ Local embedding server running")
    except Exception as e:
        print(f"✗ Local embedding server not responding: {e}")
        print("  Start it with: ./scripts/start_embedding_server.sh")
else:
    print(f"ℹ EMBED_BACKEND={EMBED_BACKEND!r}: skipping local embedding-server check.")
    # Sanity-check the API embedding endpoint instead.
    try:
        _probe = build_gemini_embed_model(
            base_url=GEMINI_EMBEDDING_BASE_URL, api_key=GEMINI_EMBEDDING_API_KEY,
            model_name=GEMINI_EMBEDDING_MODEL, dimensions=GEMINI_EMBEDDING_DIM)
        _v, _ = _probe.fn(_probe, "בדיקה")
        print(f"✓ API embeddings ({GEMINI_EMBEDDING_MODEL}): dim={len(_v[0])}")
    except Exception as e:
        print(f"✗ API embedding model not responding: {e}")

chat = OpenAI(base_url=CHAT_BASE_URL, api_key=CHAT_API_KEY)
resp = chat.chat.completions.create(model=CHAT_MODEL, messages=[{"role": "user", "content": "השב בעברית: שלום"}], max_tokens=200)
print(f"✓ Chat API ({CHAT_MODEL}): {resp.choices[0].message.content}")

ℹ EMBED_BACKEND='gemini': skipping local embedding-server check.
✓ API embeddings (gemini-embedding-2-preview): dim=3072
✓ Chat API (gemini-3.5-flash-lite): שלום! מה שלומך? איך אפשר לעזור לך היום?

## 2. Load dataset and prepare (shared pipeline)

Extraction and chunking come from the shared `lawsofisrael` package — identical
to the baseline. Each chunk keeps its `source_spans` provenance for evidence
linking.

In [5]:
from datasets import load_dataset

dataset = load_dataset(CORPUS_ID, split='train')
df = dataset.to_pandas()
if N_BILLS:
    df = df.head(N_BILLS)
print(f"Preparing {len(df)} bills (N_BILLS={N_BILLS})")

records = [extraction.extract_bill(row.to_dict(), EXTRACTION_CACHE)
           for _, row in df.iterrows()]
success = sum(r['status'] == 'success' for r in records)
print(f"Extraction: {success}/{len(records)} successful")

chunk_objs = chunking.chunk_records(records, CHUNK_TOKENS)
chunk_records = chunking.chunks_to_records(chunk_objs)
chunks_df = pd.DataFrame(chunk_records)
assert chunks_df['tokens'].max() <= CHUNK_TOKENS, 'chunk exceeds token budget'
print(f"Built {len(chunks_df)} chunks from {chunks_df['bill_id'].nunique()} bills")
chunks_df[['chunk_id', 'bill_id', 'name', 'heading_path', 'page_no', 'tokens']].head()

Preparing 100 bills (N_BILLS=100)
Extraction: 100/100 successful
Built 100 chunks from 100 bills

,chunk_id,bill_id,name,heading_path,page_no,tokens
0,1057303:0000,1057303,חוק לתיקון פקודת בתי הסוהר (הארכת הוראות שעה) ...,ספר החוקים,1,2276
1,2229019:0000,2229019,חוק נוכחות עורך דין בחקירת קטינים ואנשים עם מו...,ספר החוקים,1,20418
2,2240475:0000,2240475,"חוק לתיקון פקודת העיריות (מס' 163), התשפ""ו–2026",ספר החוקים,1,1089
3,2240465:0000,2240465,"חוק התכנון והבנייה (תיקון מס' 170), התשפ""ו-2026",,1,724
4,1057405:0000,1057405,חוק לתיקון ולהארכת תוקפן של תקנות שעת חירום (ח...,חוק לתיקון ולהארכת תוקפן של תקנות שעת חירום )ח...,2,1212

## 3. Build LLooM session and v2.1 custom prompts

The chat + local embedding models are built by the shared `make_lloom_session`.
`prompts_v2.make_custom_prompts` supplies the default quote filter, the v2.1
**free-form context-rich summarize** prompt, and the condition-faithful
**synthesize** prompt. We record both prompt versions/hashes for the manifest.

In [6]:
import builtins, contextlib

@contextlib.contextmanager
def auto_confirm():
    orig = builtins.input
    builtins.input = lambda _: 'y'
    try:
        yield
    finally:
        builtins.input = orig

session = make_lloom_session(
    chunks_df,
    model_config=MODEL_CONFIG,
    chat_base_url=CHAT_BASE_URL,
    chat_api_key=CHAT_API_KEY,
    max_output_tokens=MAX_OUTPUT_TOKENS,
    embed_url=EMBED_URL,
    embed_model_name=EMBED_MODEL,
    embed_api_key=EMBED_API_KEY,
)

custom_prompts = prompts_v2.make_custom_prompts(session)
PROMPT_INFO = prompts_v2.prompt_info()
SUMMARIZE_PROMPT_HASH = PROMPT_INFO['summarize_prompt_hash']
print("Summarize prompt:", PROMPT_INFO['summarize_prompt_version'], SUMMARIZE_PROMPT_HASH)
print("Synthesize prompt:", PROMPT_INFO['synthesize_prompt_version'], PROMPT_INFO['synthesize_prompt_hash'])

Summarize prompt: v2.1.2 e5d090a14eda
Synthesize prompt: v2.0.0 c141b3edbbe5

## 4. Distill only: quote filter + context-rich summaries

`diag.run_distill` runs **only** the distill stage (default quote filter, then
the v2.1 summary prompt). It stops before clustering so we can inspect the exact
bullets that will be embedded. This is the deliberate break in LLooM's usual
one-shot `gen`.

In [7]:
print(f"Distilling {len(chunks_df)} chunks (filter + context-rich summaries)...")
with auto_confirm():
    df_bullets = await diag.run_distill(session, custom_prompts, GEN_PARAMS)

print(f"Produced {len(df_bullets)} bullet rows")
df_bullets.head(10)

Distilling 100 chunks (filter + context-rich summaries)...
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "חוק לתיקון פקודת העיריות )מס' 163(, התשפ"ו20261052 תיקון עקיף: חוק התכנון והבנייה, התשכ"ה19651965- מס' 171",
        "1 תיקון סעיף 252א . .1 בפקודת העיריות , בסעיף 252א, אחרי \"לא תטיל עירייה\" יבוא \"היטלים כמפורט להלן\"",
        "\")2( בתקופה שמיום ט"ז בסיוון התשפ"ו )1 ביוני 2026( עד יום ה' בטבת התשצ"א )31 בדצמבר 2030(, היטל בשל מערכת תיעול או בשל סלילת כבישים, מדרכות או רחובות, ובלבד שהמיתקן משמש לקירוי שטח או מבנה ושהיטלים כאמור שהוטלו בשל השטח או המבנה האמור - שולמו . \"",
        "2 1965 . .2 בתקופה של שנה מיום תחילתו של חוק זה, יקראו את חוק התכנון והבנייה, התשכ"ה-, כך שבתוספת השלישית, בסעיף 19)ב(, אחרי פסקה )14( יבוא:",
        "״)15( השבחה במקרקעין בשל הקמת מיתקן אגרו־וולטאי. . ״"
    ]
}
```
ERROR json_load on: {
    "relevant_quotes": [
        "חוק לתיקון ולהארכת תוקפן של תקנות שעת חירום )חרבות ברזל( )פגישה עם עורך דין של עצור בעבירת ביטחון( )תיקון מס' 8(, התשפ"ו2026--1044",
        "במקום \"י\"ז באב התשפ"ו 1 דין של עצור בעבירת ביטחון(, התשפ"ד2024)31 ביולי 2026(\" יבוא \"כ\"ג בשבט התשפ"ז )31 בינואר2027(\"",
        "בנימין נתניהו ראש הממשלה",
        "אמיר אוחנה יושב ראש הכנסת",
        "יצחק הרצוג נשיא המדינה"
    ]
}
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "חוק מימון מפלגות )תיקון מס' 46 - הוראת שעה(, התשפ"ו2026774",
        "מימון הבחירות -1 . 1 הוראת שעה לעניין הבחירות לכנסת העשרים ושש יקראו את חוק מימון מפלגות, התשל"ג1973)להלן - חוק המימון(, כך:",
        "הלוואות לסיעות 2 -. .2 על אף האמור בסעיף 7ג לחוק המימון ובסעיף 4)א( לחוק התפזרות הכנסת העשרים -הוראת שעה וארבע ומימון מפלגות, התשפ"ב2022-",
        "פגרת הבחירות 3 פגרת ה בכנסת העשרים המימון וחמש .",
        "תחילה 4 . ו 4 ח תחילתו של חוק זה ביום קבלתו בכנסתה ביום קבלתו בכנסת. ."
    ]
}
```
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "חוק היועץ המשפטי לממשלה )חוות דעת, ייצוג ופיקוח(, התשפ"ו-2026",
        "במתן ייעוץ משפטי לממשלה, היועץ המשפטי לממשלה יסייע לממשלה בכל אלה: )1( להגשים את מדיניות הממשלה ויעדיה",
        "הסמכות לקבוע את עמדת הרשות המבצעת בכל הליך המתנהל בפני בית משפט, דרך כלל או להליך מסוים, נתונה בידי הממשלה, והיא תיקבע בידי היועץ המשפטי לממשלה, אלא אם כן קבעה הממשלה עמדה אחרת.",
        "על אף האמור בכל דין, כל גוף של המדינה שאינו חלק מהרשות המבצעת, לא ייוצג בפני בית משפט בידי היועץ המשפטי לממשלה אלא בהסכמת היועץ המשפטי לממשלה ובהסכמת אותו הגוף",
        "היועץ המשפטי לממשלה נושא באחריות למילוי תפקידו בפני הממשלה, והוא נתון לפיקוחו של השר מטעמה."
    ]
}
```
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "חוק שירות ביטחון )תיקון מס' 28 -הוראת שעה(, התשפ"ו2026754",
        "מטרה - פרק ג'1 26ב . מתוך הכרה בחשיבות לימוד התורה, נקבע בזה הסדר מיוחד, בהוראת שעה, להקפאת מעצרם של תלמידי ישיבות שתורתם אומנותם .",
        "תנאים להגדרת תלמיד ישיבה 26ד. ד. תלמיד ישיבה הוא מי שמתקיימים בו כל אלה:",
        "הקפאת הליכי מעצר, חקירה או אכיפה 26ז. לא יינקטו הליכי מעצר, חקירה או אכיפה בעבירות לפי סעיף 46 או לפי סעיפים 92 או 94 לחוק השיפוט הצבאי, התשט"ו , 1955- כלפי כל אלה:",
        "רשימת הישיבות 26ו"
    ]
}
```
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "חוק נתוני אשראי )תיקון מס' 6(, התשפ"ו2026--916 תיקונים עקיפים:",
        """לקוח" - יחיד או תאגיד;""",
        """תאגיד" - תאגיד שהוראות החוק חלות לגביו מכוח כללים שקבע הנגיד לפי סעיף 112;""",
        "54א . )א( הנגיד רשאי לקבוע בכללים, בדרך האמורה בסעיף , 112 כי מקורות מידע יעבירו למאגר גם נתוני אשראי לגבי תאגידים שאינם מועברים למאגר לפי סעיף , ,19 וגם נתונים שאינם נתוני אשראי, לגבי תאגידים, הדרושים לבנק ישראל לשם ביצוע תפקידיו לפי דין, כפי שיקבע...",
        "תחילתו של חוק זה שישה חודשים מיום פרסומו )בסעיף זה - יום התחילה(..."
    ]
}
```
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "חוק זיכרון הטבח והנצחת הגבורה ביום כ"ב בתשרי )שמחת תורה( -7 באוקטובר, התשפ"ו2026--876",
        "מטרתו של חוק זה להנחיל לדורות את זיכרון הטבח ולהנציח את מעשי הגבורה שאירעו ביום כ"ב בתשרי התשפ"ד )שמחת תורה( - 7 באוקטובר 2023 ובימים הסמוכים לו",
        "כ"ב בתשרי הוא יום זיכרון ממלכתי לטבח ולגבורה בכ"ב בתשרי - 7 באוקטובר",
        "מוקמת בזה רשות זיכרון לטבח ולגבורה בכ"ב בתשרי - 7 באוקטובר",
        "הרשות תקים ותפעיל אתר הנצחה וזיכרון לאומי לאירועי כ"ב בתשרי - 7 באוקטובר בנגב המערבי"
    ]
}
```
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "חוק התקנים )תיקון מס' 21(, התשפ"ו2026-",
        """האסדרה האמריקאית המאומצת" -ההוראות המחייבות החלות ברמה הפדרלית בארצות הברית המנויות בתוספת השמינית על עדכוניהן לפי סעיף 9א8, ובבהתאם למועדי התחילה הקבועים בה...",
        "תיקון פקודת היבוא והיצוא מס' 8",
        "9א . .7 )א( אימוץ אסדרה אמריקאית לפי פרק זה הוא רק לעניין עוסק שבחר לפעול על פי הוראות סעיף 9)א()1()ה( )בחוק זה -המסלול האמריקאי( .",
        "תוספת שמינית"
    ]
}
```
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "חוק משק הדלק )קווי תשתית(, התשפ"ו2026844 תיקון עקיף: חוק התכנון והבנייה, התשכ"ה19651965- מס' 168",
        "\"בעל מיתקן תת־קרקעי\" - המקים או המפעיל מיתקן תת־קרקעי, שהוא אחד מאלה:",
        "רשאי בעל המיתקן התת־קרקעי וכל מי שפועל מטעמו, לשם הקמה, הפעלה או תחזוקה של המיתקן, ובכפוף להוראות סעיף 3, להיכנס למקרקעין שבהם נמצא המיתקן, ולעניין פסקאות )1(, )4(, )8( ו–)11( עד )13( שלהלן - גם למקרקעין הסמוכים למקרקעין כאמור, ולבצע בהם את הפעולות המפורטות להלן",
        "בעל מקרקעין המתנגד לביצוע פעולות לפי סעיף 2, רשאי לפנות בהשגה למנהל בתוך התקופה המנויה בסעיף 3)א( או )ב(, לפי העניין.",
        "נגרם נזק כתוצאה מביצוע הפעולות כאמור בסעיף קטן )א(, ישלם בעל המיתקן התת־קרקעי, לפי דרישת הניזוק, פיצויים על הנזק שנגרם ."
    ]
}
```
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "הוספת סעיף 4כג . .1 בחוק רשות מקרקעי ישראל, התש"ך1960-",
        "רשות מקומית המשתייכת לדירוג 1 עד 5 לפי מדד הפריפריאליות שקיבלה מענק כללי לאיזון ממשרד הפנים בכל אחת משלוש השנים שקדמו לשנת הכספים שבה הוגשה הבקשה, רשאית לבקש מרשות מקרקעי ישראל, לפי החלטת מועצת אותה רשות מקומית, להקצות לה קרקע בתחומה לשם הקמה והפעלה של מיזם",
        "הרשות תקצה לרשות מקומית שהגישה בקשה, קרקע להקמה והפעלה של מיזם, בהתקיים כל אלה",
        "על אף האמור בסעיף 2 לחוק חובת המכרזים, התשנ"ב- , הקצאת קרקע על ידי הרשות לפי סעיף זה אינה טעונה מכרז, ויראו הוראות סעיף זה כאילו היו הוראות בדבר פטור ממכרז שנקבעו לפי החוק האמור",
        "מועצת מקרקעי ישראל תקבע כללים לפי סעיף 4כג)ח( לחוק העיקרי כנוסחו בחוק זה"
    ]
}
```
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "חוק הרשות לפיתוח הנגב )תיקון מס' 4( )תיקון מס' 2(, התשפ"ו2026",
        "תיקון סעיף 5 . .1 בחוק הרשות לפיתוח הנגב )תיקון מס' 4(, התש"ע2010שנים\" יבוא \" 17 שנים\"",
        "בצלאל סמוטריץ' שר האוצר",
        "בנימין נתניהו ראש הממשלה",
        "יצחק שמעון וסרלאוף שר הנגב הגליל והחוסן הלאומי"
    ]
}
```
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "חוק לקידום הבנייה במתחמים מועדפים )הוראת שעה( )תיקון מס' 9(, התשפ"ו2026836",
        ". .1 בחוק לקידום הבנייה במתחמים מועדפים )הוראת שעה(, התשע"ד2014העיקרי(, בסעיף27)ג()2(, המילים \"או התקופה המנויה בסעיף 34)ד(, אם הוארכה\" יימחקו .",
        ". .2 בסעיף 34 לחוק העיקרי -",
        ")1( בסעיף קטן )ג(, במקום \"ארבע\" יבוא \"שש\";",
        ")2( סעיף קטן )ד( -בטל ."
    ]
}
```
ERROR json_load on: {
    "relevant_quotes": [
        "בחוק הכניסה לישראל, התשי"ב1952-",
        "תיקון סעיף",
        "הוספת סעיף 14א",
        "\"שימוש בהכנסה מאגרה בעד הגשת בקשה לאישור\nל ק\nמסע אלקטרוני",
        "אישור מסע אלקטרוני"
    ]
}
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "חוק תקשורת דיגיטלית עם גופים ציבוריים )תיקון מס' 5(, התשפ"ו2026832",
        """מסר קולי מוקלט" - מסר אלקטרוני הנשלח בהקראה קולית כשיחה טלפונית למספר טלפון נייד ממספר טלפון מזוהה;""",
        "")9( בלי לגרוע מהוראות לפי חוק שוויון זכויות לאנשים עם מוגבלות, התשנ"ח , 1998לעניין מסר שנשלח למספר טלפון נייד מאחד מהגופים הציבוריים האלה בלבד: רשות המסים בישראל, רשות האוכלוסין וההגירה והמוסד לביטוח לאומי - אם מספר הטלפון שאליו נשלח המסר אינו מקבל מסרונים, המסר יישלח אליו כמסר קולי מוקלט באחת מהדרכים האלה:""",
        "תחולה מדורגת . .5 הוראות סעיפים 3ג)א()9( ו־3יא)ז( לחוק העיקרי, כנוסחם בחוק זה, יכול שיחולו על שליחת מסרים מאת רשות המסים בישראל, רשות האוכלוסין וההגירה והמוסד לביטוח לאומי, למספר טלפון שאינו מקבל מסרונים, בהדרגה, ובלבד שיתקיימו שני אלה:",
        "איסוף מידע ראשון . .6 איסוף ראשון של מידע לפי סעיף 3טו)א()4( לחוק העיקרי, כנוסחו בחוק זה, יחול החל משנת2027 ואילך. ך."
    ]
}
```
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "1 )להלן - החוק העיקרי(, בסעיף 24)א()2(, המילים . .1 בחוק אומנה לילדים, התשע"ו2016"וטרם מלאו לו 56 שנים" -יימחקו .",
        ". .2 בסעיף 63 לחוק העיקרי, סעיף קטן )ג( - בטל .",
        ". .3 בתוספת הראשונה לחוק העיקרי, אחרי פרט 3 יבוא:",
        ". .4 בתוספת השנייה לחוק העיקרי, בפרט , ,5 הסיפה החל במילים "ובכלל זה" -תימחק .",
        ". .5 שר הרווחה והביטחון החברתי ימסור לוועדת העבודה והרווחה של הכנסת, אחת לחצי שנה, במשך שנתיים מיום תחילתו של חוק זה, נתונים כלהלן לגבי חצי השנה שקדמה למועד הדיווח:"
    ]
}
```
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "חוק זכויות הסטודנט )תיקון מס' 12(, התשפ"ו2026--826",
        "תיקון סעיף 4 . .1 בחוק זכויות הסטודנט, התשס"ז2007--לימודים לתואר ראשון, לתואר שני ולתואר שלישי, ובלבד שבמסלולי הלימוד הנפרדים במוסדות שאינם מוסדות נפרדים ההפרדה תהיה בכיתות הלימוד בלבד",
        "לא יראו קבלת מועמדים למוסד נפרד או למסלול לימודים נפרד לגברים ולנשים מטעמי דת שהוראות סעיף קטן זה חלות עליו, כהפליה לפי חוק המועצה להשכלה גבוהה",
        "יואב קיש שר החינוך",
        "בנימין נתכין ראש הממשלה"
    ]
}
```
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "בחוק זכויות הסטודנט, התשס"ז2007--במקום \"מין\" יבוא \"מין, נטייה מינית, זהות מגדרית\" .",
        "תיקון סעיף 4",
        "תיקון סעיף 19א . .2 בסעיף 19א לחוק העיקרי -",
        "תקנות וכללים ראשונים . .3 תקנות וכללים ראשונים לפי סעיף קטן )א( שבסעיף 19א לחוק העיקרי",
        "בנימין נתניהו ראש הממשלה"
    ]
}
```
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "בחוק חופשה שנתית, התשי"א1951--",
        "יום האזכרה של אדם שנפטר -לגבי קרוב משפחתו",
        "יריב לוין\n\nשר המשפטים",
        "בנימין נתניהו ראש הממשלה",
        "יצחק הרצוג נשיא המדינה"
    ]
}
```
ERROR json_load on: {
    "relevant_quotes": [
        "חוק לתיקון פקודת המועצות המקומיות )מס' 82(, התשפ"ו2026760",
        "רשאי השר להכריז, בצו, כי כפר פלוני או קבוצת כפרים פלונית או אזור פלוני יתנהלו על ידי מועצה מקומית גם אם לא מתקיימים בהם התנאים המנויים באותו סעיף קטן",
        "השר שוכנע לאחר עיון בתסקיר של ועדת חקירה כמשמעותה בסעיף 3)א( לפקודת העיריות, כי הכפר, קבוצת הכפרים או האזור, לפי העניין, צפויים לכלול בתוך עשר שנים ממועד הקמת המועצה המקומית למעלה מעשרים אלף תושבים",
        "שר הפנים ידווח לוועדת הפנים והגנת הסביבה של הכנסת, אחת לשנה, על אופן יישומו של חוק זה",
        "* התקבל בכנסת ביום כ"ט בתמוז התשפ"ו )14 ביולי 2026("
    ]
}
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "חוק שיקום נרחב לחבל התקומה כאזור מיקוד לאומי וסיוע ליישובים הסמוכים אליו )תיקון מס' 2(, התשפ"ו2026--750",
        "תיקון סעיף 27 . .1 בחוק שיקום נרחב לחבל התקומה כאזור מיקוד לאומי וסיוע ליישובים הסמוכים אליו, , בסעיף , ,27 אחרי סעיף קטן )ג( יבוא: 1 התשפ"ה2025-",
        "\")ג1( נוסף על האמור בסעיף קטן )ג(, לשם קיום התחייבויות קודמות שניתנו למועצה האזורית שדות נגב ובמסגרת השיקום הנרחב, תעביר המינהלת למועצה האמורה, באופן חד־פעמי, סכום של 20 מיליון שקלים חדשים, מתקציב המינהלת, בתוך חודשיים מיום פרסומו של חוק שיקום נרחב לחבל התקומה כאזור מיקוד לאומי וסיוע ליישובים . \"",
        "בנימין נתניהו ראש הממשלה",
        "יצחק הרצוג נשיא המדינה"
    ]
}
```
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "חוק הספורט )תיקון מס' 17(, התשפ"ד2024ד958 תיקון עקיף: חוק בתי משפט לעניינים מינהליים, התש"ס2000- - מס' 143",
        "2 )להלן - החוק העיקרי(, במקום סעיף 1 יבוא: החלפת סעיף 1 . .1 בחוק הספורט, התשמ"ח1988--"הגדרות . .1 בחוק זה -",
        "לא יעסוק אדם, בין בתמורה וbetween שלא בתמורה, באימון ספורט, בסוג של פעילות ספורט ובתנאים שלגביהם קבע השר לפי סעיף 2א כי נדרשת תעודת הסמכה, אלא אם כן יש בידו תעודת הסמכה כנדרש לפי אותו סעיף והוא רשום במרשם .",
        "השר רשאי לקבוע סוגי פעילות ספורט שבהם לא יוכל אדם לעסוק באימון ספורט, אלא אם כן יש בידו תעודת הסמכה לאותו סוג של פעילות ספורט",
        "אדם העורך הכשרה בסוג פעילות ספורט מוסדר, בלא שקיבל הכרה כמוסד מוכר להכשרה, בניגוד להוראות סעיף 4א"
    ]
}
```
ERROR json_load on: {
    "relevant_quotes": [
        "חוק כליאתם של לוחמים בלתי חוקיים )תיקון מס' 4 והוראת שעה - חרבות ברזל( )תיקון מס' 8(, התשפ"ו2026746",
        "תיקון סעיף 2 . .1 בחוק כליאתם של לוחמים בלתי חוקיים )תיקון מס' 4 והוראת שעה - חרבות ברזל(, , בסעיף 2 -1 התשפ"ד2023-",
        "במקום \"ט\"ו בתמוז התשפ"ו )30 ביוני 2026(\" יבוא \"י\"ט בתשרי התשפ"ז )30 בספטמבר 2026(\";",
        ". .2 )א( תחילתו של חוק זה ביום ט\"ז בתמוז התשפ"ו )1 ביולי 2026( )להלן - יום התחילה( .",
        "עד יום י\"ט בתשרי התשפ"ז )30 בספטמבר 2026(, ויראו את ההכרזה האמורה כאילו ניתנה לפי הסעיף האמור."
    ]
}
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "חוק הסדרת העיסוק במקצועות הבריאות )תיקון מס' 8(, התשפ"ג2023--704",
        "\"דימות רפואי\" - הפקת דמות לשם אבחון רפואי או טיפול רפואי באדם, באמצעות קרינה מייננת, גלי קול )אולטרסאונד( או מגנט )MRI;) \"דימותן רפואי\" -מי שניתנה לו תעודת דימותן רפואי;",
        "\"עמית רופא\" - מי שניתנה לו תעודת עמית רופא;",
        "רופא מומחה רשאי לתת לעמית רופא הרשאה אישית לבצע בפיקוחו פעולות רפואיות שהן בענף המומחיות של הרופא המומחה ועיסוקו בפועל",
        "תחילתו של חוק זה שנה מיום פרסומו )בחוק זה - יום התחילה(;"
    ]
}
```
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "\"חוק הנכים\" - חוק הנכים )תגמולים ושיקום(, התשי"ט1959- ]נוסח משולב[, לרבות הוראות החוק האמור כפי שהוחלו לפי חוקים אלה:",
        "\"תביעה לתגמול עיקרי\" - תביעה לקביעת דרגת נכות ולקבלת תגמול עיקרי, לרבות בקשה להכרה;",
        "על אף האמור בכל דין או הסכם, לא יידרש אדם לשלם בעד טיפול בתביעה לתגמול עיקרי שכולל בקשה להכרה ובעקבותיה הליכים לפני ועדה רפואית, סכום העולה על דמי פתיחת תיק כאמור בפסקה )1( שלהלן",
        "על אף האמור בכל דין או הסכם, לא יידרש אדם לשלם תשלום בעד טיפול בהליך ערעור.",
        "כל התקשרות לעניין טיפול בתביעה לקבלת תגמולים בעד תשלום תמורה תהיה בהסכם בכתב, באותיות ברורות וקריאות ובשפה המובנת למי שמבקש טיפול בתביעה;"
    ]
}
```
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "חוק הכרה בתרומתם של כלבים ששירתו בגופים ביטחוניים, התשפ"ו2026624",
        "מטרתו של חוק זה להכיר בתרומתם של כלבים ששירתו בגופים ביטחוניים לביטחון ישראל, להצלת חיילי צבא הגנה לישראל ולשמירת שלום הציבור, ולהבטיח את רווחתם לאחר סיום שירותם כאות הוקרה על גבורתם ופועלם במילוי תפקידם .",
        "כלב ששירת בגוף ביטחוני, יהיה בעליו זכאי להחזר הוצאות מהמדינה בעד ההוצאות הרפואיות הנדרשות לטיפול בכלבו;",
        "החזר הוצאות רפואיות לטיפול בכלב לפי סעיף זה לא יעלה על 5,000 שקלים חדשים בשנה, ויותנה בהוכחת תשלום בפועל;",
        "תחילתו של חוק זה שלושים ימים מיום פרסומו ."
    ]
}
```
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "בחוק בתי המשפט ]נוסח משולב[, התשמ"ד1984-",
        "הוספת סעיף 24א . .1",
        "ביקור שופט בבית סוהר",
        "במהלך שנת כהונתו הראשונה יבקר שופט בבית סוהר או במקום מעצר שבאחריות שירות בתי הסוהר",
        "תחילה . .2 תחילתו של חוק זה ביום י"ט באלול התשפ"ו )1 בספטמבר 2026("
    ]
}
```
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "תיקון שם החוק . .1 בחוק להקפאת כספים ששילמה הרשות הפלסטינית בזיקה לטרור מהכספים המועברים 1 )להלן - החוק העיקרי(, בשם החוק, במקום אליה מממשלת ישראל, התשע"ח2018\"להקפאת\" יבוא \"להקפאה וניכוי של\" .",
        "הוספת סעיף 5 . .4 אחרי סעיף 4 לחוק העיקרי יבוא:\n\n\"ניכוי כספים בשל נזקי טרור . .5 )א( שר האוצר יגיש לוועדת השרים לענייני ביטחון לאומי, עד 28 בפברואר בכל שנה, דוח שבו יפורטו כל אלה:",
        "דיווח על כספים שהוקפאו בשל העברת כספים לרצועת עזה\n\n13 . 8 , בסעיף , ,1 בהגדרה \"מחבל\", במקום בחוק גירוש משפחות מחבלים, התשפ"ה2024\"להקפאת\" יבוא \"להקפאה ולניכוי של\" .",
        "תיקון חוק האזרחות - מס' 15",
        "תחילה, תחולה והוראות מעבר"
    ]
}
```
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "חוק העונשין )תיקון מס' 154(, התשפ"ו2026--610 תיקון עקיף: חוק סדר הדין הפלילי )סמכויות אכיפה - מעצרים(, התשנ"ו1996- - מס' 25",
        "סימן ו':1 פגיעה בריבונות המדינה באמצעות הכנסה או הוצאה של דבר בגבולות",
        "122א . המכניס דבר לישראל שלא כדין או המוציא מישראל דבר שלא כדין, שלא דרך תחנת גבול, דינו - מאסר תשע שנים; בסעיף זה, \"תחנת גבול\" - תחנת גבול שקבע שר הפנים בצו .",
        "בנימין נתניהו ראש הממשלה",
        "יריב לוין שר המשפטים"
    ]
}
```
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "חוק הטבות מס ליישוב אזור קו עימות מזרחי )הוראת שעה(, התשפ"ו2026606 תיקון עקיף: פקודת מס הכנסה -הוראת שעה - מס' 292",
        "\"אזור קו עימות מזרחי\" -האזור הממוקם מזרחית לגדר המסומנת במפה שבתוספת, וכל עוד היא עומדת בתוקף בהתאם למדיניות הממשלה;",
        "\"יישוב אזור קו עימות מזרחי מוטב\" -יישוב שב־31 בדצמבר שלפני שנת המס שלגביה ניתן הזיכוי לפי חוק זה, מתקיימים בו כל אלה:",
        "תחילתו של חוק זה ביום י"ב בטבת התשפ"ו )1בינואר 2026(, והוא יעמוד בתוקף עד יום א' בטבת התשפ"ח )31 בדצמבר 2027(; השר, באישור ועדת הכספים של הכנסת, רשאי, בצו, להאריך את תוקפו של חוק זה לתקופות נוספות שלא יעלו על שנתיים כל אחת, בהתאם למדיניות הממשלה.",
        "")ב4( מי שהיה במשך כל שנת המס תושב יישוב אזור קו עימות מזרחי מוטב, כהגדרתו , זכאי 4 בחוק הטבות מס ליישוב אזור קו עימות מזרחי )הוראת שעה(, התשפ"ו2026באותה שנה לזיכוי ממס בשיעור כאמור בפסקה )1( שבסעיף קטן )ב( עד לתקרה הקבועה באותה פסקה, ובלבד שאם הוא זכאי באותה שנה לזיכוי כאמור וכן לזיכוי אחר לפי הוראות סעיף זה, הברירה בידו לבחור באחד מהם . ""
    ]
}
```
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "חוק התכנון והבנייה )תיקון מס' 162 -הוראת שעה(, התשפ"ה2025720",
        "תיקון סעיף 62א -הוראת שעה 1 )להלן - החוק העיקרי(, כך שבסעיף 62א -. .1 בתקופה של חמש שנים מיום פרסומו של חוק זה )להלן - תקופת הוראת השעה( יקראו את חוק התכנון והבנייה, התשכ"ה1965--",
        "שינוי ייעודה של קרקע בתחום יישוב קיים הנמצאת בתחומה של מועצה אזורית במחוז הצפון או במחוז הדרום, לקרקע המיועדת למגורים ולשימושים הנדרשים בעיקר ובמישרין לתוספת יחידות הדיור",
        "שטח הקרקע שייעודה ישונה לפי פסקה זו לא יעלה על 20 דונם בכל יישוב;",
        "הוראות מעבר 2 )א( תוכנית שהוגשה למוסד התכנון שערב יום תחילתו של חוק זה )להלן - יום התחילה(, הסמכות לגביה הייתה נתונה לוועדה מחוזית לתכנון ולבנייה"
    ]
}
```
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "חוק זכויות מבצעים ומשדרים )תיקון מס' 10(, התשפ"ו2026--586",
        "ביצוע פומבי מותר בכפוף לתשלום תמלוג ראוי למבצע .",
        "המבצע הוא הבעלים הראשון של זכות המבצעים בביצוע .",
        "זכות מבצעים ניתנת להעברה בחוזה או על פי דין, ורשאי בעל הזכות לתת לגביה רישיון ייחודי או רישיון שאינו ייחודי. .",
        "תקציב לתמיכה באמנים במצוקה ייקבע בסעיף תקציב משרד התרבות והספורט בחוק תקציב שנתי"
    ]
}
```
ERROR json_load on: ```json
{
    "relevant_quotes": [
        "חוק ביטוח בריאות ממלכתי )תיקון מס' 75(, התשפ"ו2026",
        "תיקון עקיף: חוק מגן דוד אדום, התש"י19501950- מס' 11",
        "יקבל המבוטח החזר של 80% מההוצאה, עד לסכום השווה ל־80% מהאגרה הקבועה בתקנות אגרות הסעת חירום באמבולנס",
        "בתוספת זו, \"מחלה או הפרעה נפשית קשה\" )Illness Mental Severe )אחת מאלה: סכיזופרניה, הפרעה דו־קוטבית, הפרעה סכיזו־אפקטיבית",
        "תחילתו של חוק זה שלושה חודשים מיום פרסומו, והוא יחול על הסעה או הזעקת אמבולנס שבוצעה ביום תחילתו או לאחריו"
    ]
}
```
ERROR json_load on: {
    "relevant_quotes": [
        "חוק דיווח לכנסת על הטרדות מיניות בכוחות הביטחון והטיפול בהן )תיקוני חקיקה(, התשפ"ו202542",
        "המפקח הכללי יגיש לוועדה לביטחון לאומי של הכנסת, עד 31 במרץ בכל שנה, דין וחשבון לגבי השנה הקלנדרית שקדמה למועד הדיווח",
        "הנציב יגיש לוועדה לביטחון לאומי של הכנסת, עד 31 במרץ בכל שנה, דין וחשבון לגבי השנה הקלנדרית שקדמה למועד הדיווח",
        "הרמטכ"ל יגיש לוועדת החוץ והביטחון של הכנסת, עד 31 במרץ בכל שנה, דין וחשבון לגבי השנה הקלנדרית שקדמה למועד הדיווח",
        "בדין וחשבון האמור לא ייכללו פרטי מידע שיאפשרו את זיהוי המדווח, המתלונן או הנילון ואנשים אחרים המעורבים בדיווח"
    ]
}
ERROR json_load on: ```json
{
    "relevant_quotes": [

       chunk_id                                               text
0  1057303:0000  הארכת הוראות השעה לתיקון פקודת בתי הסוהר בהתאם...
1  1057303:0000  תיקון מספר 64 לפקודת בתי הסוהר במסגרת הוראת שע...
2  1057303:0000  תיקון מספר 66 לפקודת בתי הסוהר במסגרת הוראת שע...
3  1057303:0000  הארכת תוקף הכרזה שניתנה לפי סעיף 19כ לפקודת בת...
4  2229019:0000  תיקון חוק הליכי חקירה והעדה מס' 5 לאנשים עם מו...
5  2229019:0000  תיקון חוק הנוער ענישה ודרכי טיפול הוראת שעה מס...
6  2229019:0000     התרת זכות לנוכחות עורך דין במהלך חקירה משטרתית
7  2229019:0000          התרת התחלת חקירה ללא המתנה להגעת עורך דין
8  2229019:0000      הסדרת התנהלותו של עורך דין הנוכח בפועל בחקירה
9  2240465:0000     הוספת המילה ממסחר אחרי מתעסוקה ברישה של פסקה 1

## 5. Pre-clustering bullet artifact + accounting

Capture the exact bullet corpus with stable ids and chunk linkage, and account
honestly for chunks that produced **no** bullet (a proxy for malformed/empty
model JSON that LLooM otherwise drops silently).

In [8]:
RUN_META = {'corpus_id': CORPUS_ID, 'summarize_prompt_hash': SUMMARIZE_PROMPT_HASH}
bullet_rows = diag.build_bullet_artifact(
    session, prompt_info=PROMPT_INFO, run_meta={'corpus_id': CORPUS_ID})
diag.validate_bullet_artifact(bullet_rows, chunk_ids=set(chunks_df['chunk_id']))

ACCOUNTING = diag.bullet_accounting(session)
print("Bullet accounting:", ACCOUNTING)

bullets_df = pd.DataFrame(bullet_rows)
DIAG_DIR.mkdir(parents=True, exist_ok=True)
bullets_df.to_parquet(DIAG_DIR / 'bullets_v2.parquet', index=False)
print(f"Wrote {len(bullets_df)} bullets -> {DIAG_DIR / 'bullets_v2.parquet'}")
bullets_df[['bullet_row_id', 'chunk_id', 'bullet']].head(10)

Bullet accounting: {'n_input_chunks': 33, 'n_chunks_with_bullets': 33, 'n_chunks_without_bullets': 0, 'n_bullets': 170, 'chunk_ids_without_bullets': []}
Wrote 170 bullets -> /home/nick/Documents/projects/lawsofisrael/notebooks/outputs/diagnostics/bullets_v2.parquet

,bullet_row_id,chunk_id,bullet
0,1057303:0000#b000,1057303:0000,הארכת הוראות השעה לתיקון פקודת בתי הסוהר בהתאם...
1,1057303:0000#b001,1057303:0000,תיקון מספר 64 לפקודת בתי הסוהר במסגרת הוראת שע...
2,1057303:0000#b002,1057303:0000,תיקון מספר 66 לפקודת בתי הסוהר במסגרת הוראת שע...
3,1057303:0000#b003,1057303:0000,הארכת תוקף הכרזה שניתנה לפי סעיף 19כ לפקודת בת...
4,2229019:0000#b000,2229019:0000,תיקון חוק הליכי חקירה והעדה מס' 5 לאנשים עם מו...
5,2229019:0000#b001,2229019:0000,תיקון חוק הנוער ענישה ודרכי טיפול הוראת שעה מס...
6,2229019:0000#b002,2229019:0000,התרת זכות לנוכחות עורך דין במהלך חקירה משטרתית
7,2229019:0000#b003,2229019:0000,התרת התחלת חקירה ללא המתנה להגעת עורך דין
8,2229019:0000#b004,2229019:0000,הסדרת התנהלותו של עורך דין הנוכח בפועל בחקירה
9,2240465:0000#b000,2240465:0000,הוספת המילה ממסחר אחרי מתעסוקה ברישה של פסקה 1

In [9]:
# Trace a bullet back to its source chunk BEFORE any embedding/clustering.
chunk_lookup = v2_export.make_chunk_lookup(chunk_records)
if bullet_rows:
    b = bullet_rows[0]
    src = chunk_lookup.get(b['chunk_id'], {})
    print("BULLET:  ", b['bullet'])
    print("CHUNK_ID:", b['chunk_id'])
    print("BILL:    ", src.get('bill_id'), '-', src.get('name'))
    print("HEADING: ", src.get('heading_path'), '| page', src.get('page_no'))
    print("SOURCE (excerpt):", (src.get('text') or '')[:400])

BULLET:   הארכת הוראות השעה לתיקון פקודת בתי הסוהר בהתאם לחוק התשפ"ו-2026
CHUNK_ID: 1057303:0000
BILL:     1057303 - חוק לתיקון פקודת בתי הסוהר (הארכת הוראות שעה) (תיקוני חקיקה), התשפ"ו-2026
HEADING:  ספר החוקים | page 1
SOURCE (excerpt): ט"ו באב התשפ"ו 3575 29 ביולי 2026

עמוד

חוק לתיקון פקודת בתי הסוהר )הארכת הוראות שעה( )תיקוני חקיקה(, התשפ"ו20261048 תיקונים עקיפים: חוק לתיקון פקודת בתי הסוהר )מס' 64 - הוראת שעה - חרבות ברזל( )מצב חירום כליאתי(, התשפ"ד2023- - מס' 5 חוק לתיקון פקודת בתי הסוהר )תיקון מס' 66 - הוראת שעה - חרבות ברזל( )חופשה מיוחדת לאסיר(, התשפ"ד2024- - מס' 5

, בסעיף 1 -. .1 בחוק לתיקון פקודת בתי הסוהר )מס' 64 - ה

## 6. Nearest-neighbor explorer (summary bullets only)

Embed the bullets and inspect cosine nearest neighbors over the **raw** vectors
(self excluded) — before UMAP/HDBSCAN can distort the space. Three
representation controls (set in section 0) let you A/B what drives similarity:

- **`EMBED_BACKEND`** — `'local'` bge-m3 vs `'gemini'` API embeddings.
- **`EMBED_INSTRUCTION`** (Option 1) — a task prefix telling the embedder to
  represent the *legal effect / domain* rather than surface phrasing. Set to
  `None` to embed the bare bullet.
- **`USE_DOMAIN_CONTEXT`** (Option 2) — prepend each bullet's bill title +
  heading path so domain signal is injected explicitly.

Look at representative *extension*, *right*, and *prohibition* bullets: do their
neighbors now share population/domain/condition context, or merely a generic
verb / shared year token? Unrelated neighbors in a narrow similarity band mean
the representation still isn't separating legal concepts.

In [10]:
# Pick the embedding backend.
if EMBED_BACKEND == 'gemini':
    embed_model = build_gemini_embed_model(
        base_url=GEMINI_EMBEDDING_BASE_URL,
        api_key=GEMINI_EMBEDDING_API_KEY,
        model_name=GEMINI_EMBEDDING_MODEL,
        dimensions=GEMINI_EMBEDDING_DIM,
    )
    embed_backend_id = f"gemini:{GEMINI_EMBEDDING_MODEL}:dim={GEMINI_EMBEDDING_DIM or 'default'}"
    print(f"Embedding backend: {embed_backend_id} (bullet text is sent to the API)")
else:
    embed_model = session.cluster_model  # local bge-m3
    embed_backend_id = f"local:{EMBED_MODEL}"
    print(f"Embedding backend: {embed_backend_id} (local, no data leaves the machine)")

# Option 2: per-chunk domain context (bill title + heading path).
context_by_id = chunk_lookup if USE_DOMAIN_CONTEXT else None
# make_chunk_lookup rows use 'name' for the bill title; embed_bullets reads
# 'bill_title' or 'name', so the raw chunk records work directly.

bullet_ids, bullet_texts, bullet_emb = diag.embed_bullets(
    bullet_rows, embed_model,
    instruction=EMBED_INSTRUCTION, context_by_id=context_by_id)
neighbor_rows = diag.nearest_neighbors(bullet_ids, bullet_texts, bullet_emb, k=NN_K)
neighbors_df = pd.DataFrame(neighbor_rows)
neighbors_df.to_parquet(DIAG_DIR / 'nearest_neighbors_v2.parquet', index=False)
print(f"Wrote nearest neighbors (k={NN_K}) -> {DIAG_DIR / 'nearest_neighbors_v2.parquet'}")

def show_neighbors(bullet_id):
    for r in diag.neighbors_for(neighbor_rows, bullet_id):
        print(f"  [{r['rank']}] sim={r['similarity']:.3f}  {r['neighbor_bullet']}")

# Inspect a few probe bullets by keyword (extension / right / prohibition).
import re
def find_bullet(keyword):
    for bid, txt in zip(bullet_ids, bullet_texts):
        if re.search(keyword, txt):
            return bid, txt
    return None, None

for kw in ['הארכ', 'זכות', 'איסור']:  # extension / right / prohibition
    bid, txt = find_bullet(kw)
    if bid:
        print(f"\nQUERY ({kw}): {txt}")
        show_neighbors(bid)
neighbors_df.head(10)

Embedding backend: gemini:gemini-embedding-2-preview:dim=3072 (bullet text is sent to the API)
Wrote nearest neighbors (k=5) -> /home/nick/Documents/projects/lawsofisrael/notebooks/outputs/diagnostics/nearest_neighbors_v2.parquet

QUERY (הארכ): הארכת הוראות השעה לתיקון פקודת בתי הסוהר בהתאם לחוק התשפ"ו-2026
  [1] sim=0.967  הארכת תוקף הכרזה שניתנה לפי סעיף 19כ לפקודת בתי הסוהר עד ליום ט"ו בספטמבר 2026
  [2] sim=0.961  תיקון מספר 64 לפקודת בתי הסוהר במסגרת הוראת שעה למצב חירום כליאתי חרבות ברזל
  [3] sim=0.946  תיקון מספר 66 לפקודת בתי הסוהר במסגרת הוראת שעה לחופשה מיוחדת לאסיר בחרבות ברזל
  [4] sim=0.906  הארכת תוקף תחולה והוראת שעה עד ליום 30 ביוני 2029 במקום 1 ביולי 2024
  [5] sim=0.901  תיקון חוק קיום דיונים בהיוועדות חזותית לעצורים אסירים וכלואים הוראת שעה

QUERY (זכות): התרת זכות לנוכחות עורך דין במהלך חקירה משטרתית
  [1] sim=0.930  התרת התחלת חקירה ללא המתנה להגעת עורך דין
  [2] sim=0.927  הסדרת התנהלותו של עורך דין הנוכח בפועל בחקירה
  [3] sim=0.893  תיקון חוק הליכי חקירה והעדה מס' 5 לאנשים עם מוגבלות
  [4] sim=0.865  תיקון חוק הנוער ענישה ודרכי טיפול הוראת שעה מס' 26
  [5] sim=0.859  התניית ביצוע חיפוש משטרתי באישור קצין בדרגת רב־פקד ומעלה

QUERY (איסור): איסור על רשות ציבורית למנוע את העסקת עובדה בוועדת בחירות בהסכמתו
  [1] sim=0.850  זכות מצביע מפונה להצביע בקלפי ייעודית למפונים או בקלפי נגישה למוגבלי בניידות
  [2] sim=0.845  קביעת הוראות מיוחדות להיערכות לבחירות לכנסת העשרים ושש בע기o מצב חירום
  [3] sim=0.834  חובת צירוף גילוי ברור ובולט על תעמולת בחירות שנוצרה כנחֱזּות עמוקה
  [4] sim=0.832  סמכות יושב ראש הוועדה המרכזית לקבוע הוראות חורגות לעניין מועדים ודרכי פרסום
  [5] sim=0.825  איסור על אדם לעסק בפפעולה הטעונה רישום אלא אם הוא רשום במרשם

,bullet_row_id,bullet,rank,neighbor_id,neighbor_bullet,similarity
0,1057303:0000#b000,הארכת הוראות השעה לתיקון פקודת בתי הסוהר בהתאם...,1,1057303:0000#b003,הארכת תוקף הכרזה שניתנה לפי סעיף 19כ לפקודת בת...,0.967302
1,1057303:0000#b000,הארכת הוראות השעה לתיקון פקודת בתי הסוהר בהתאם...,2,1057303:0000#b001,תיקון מספר 64 לפקודת בתי הסוהר במסגרת הוראת שע...,0.961165
2,1057303:0000#b000,הארכת הוראות השעה לתיקון פקודת בתי הסוהר בהתאם...,3,1057303:0000#b002,תיקון מספר 66 לפקודת בתי הסוהר במסגרת הוראת שע...,0.946062
3,1057303:0000#b000,הארכת הוראות השעה לתיקון פקודת בתי הסוהר בהתאם...,4,2220910:0000#b001,הארכת תוקף תחולה והוראת שעה עד ליום 30 ביוני 2...,0.905710
4,1057303:0000#b000,הארכת הוראות השעה לתיקון פקודת בתי הסוהר בהתאם...,5,1057405:0000#b001,תיקון חוק קיום דיונים בהיוועדות חזותית לעצורים...,0.901389
5,1057303:0000#b001,תיקון מספר 64 לפקודת בתי הסוהר במסגרת הוראת שע...,1,1057303:0000#b002,תיקון מספר 66 לפקודת בתי הסוהר במסגרת הוראת שע...,0.961595
6,1057303:0000#b001,תיקון מספר 64 לפקודת בתי הסוהר במסגרת הוראת שע...,2,1057303:0000#b000,הארכת הוראות השעה לתיקון פקודת בתי הסוהר בהתאם...,0.961165
7,1057303:0000#b001,תיקון מספר 64 לפקודת בתי הסוהר במסגרת הוראת שע...,3,1057303:0000#b003,הארכת תוקף הכרזה שניתנה לפי סעיף 19כ לפקודת בת...,0.944933
8,1057303:0000#b001,תיקון מספר 64 לפקודת בתי הסוהר במסגרת הוראת שע...,4,1057405:0000#b000,תיקון חוק לתיקון ולהארכת תוקפן של תקנות שעת חי...,0.907259
9,1057303:0000#b001,תיקון מספר 64 לפקודת בתי הסוהר במסגרת הוראת שע...,5,1057405:0000#b001,תיקון חוק קיום דיונים בהיוועדות חזותית לעצורים...,0.902378

## 7. Reproducible clustering diagnostics — compare configurations

Run one or more seeded UMAP+HDBSCAN configurations. **No cluster-size cutoff is
prescribed**: define a few `ClusterConfig`s and compare their noise ratio,
cluster count, membership probabilities, and condensed-tree stability. Every run
retains raw embeddings, UMAP coordinates, the fitted estimator, labels,
probabilities, and outlier scores, and writes its condensed-tree table (plus an
optional plot and UMAP scatter, if matplotlib is installed).

In [18]:
# Candidate configurations to compare. Edit freely — this is exploration.
configs = {
    'A': diag.ClusterConfig(hdbscan_min_cluster_size=3, hdbscan_cluster_selection_method='leaf', random_state=42),
    'B': diag.ClusterConfig(hdbscan_min_cluster_size=5, hdbscan_cluster_selection_method='eom', random_state=42),
    'C': diag.ClusterConfig(hdbscan_min_cluster_size=5, hdbscan_cluster_selection_method='leaf', random_state=42),
    'D': diag.ClusterConfig(hdbscan_min_cluster_size=7, hdbscan_cluster_selection_method='eom', random_state=42),
    'E': diag.ClusterConfig(hdbscan_min_cluster_size=4, hdbscan_cluster_selection_method='leaf', random_state=42)
}


results = {}
for name, cfg in configs.items():
    try:
        res = diag.run_clustering(bullet_ids, bullet_texts, bullet_emb, cfg,
                                  bullet_prompt_hash=SUMMARIZE_PROMPT_HASH)
    except ValueError as e:
        print(f"[{name}] skipped: {e}")
        continue
    results[name] = res
    entry = diag.clustering_manifest_entry(res)
    print(f"[{name}] run_id={entry['cluster_run_id']} "
          f"n_clusters={entry['n_clusters']} noise={entry['noise_ratio']:.0%} "
          f"cross_bill={entry['n_cross_bill_clusters']} "
          f"single_bill={entry['n_single_bill_clusters']}")
    rid = res.config.run_id()
    diag.condensed_tree_table(res).to_parquet(DIAG_DIR / f'condensed_tree_{name}_{rid}.parquet', index=False)
    tree_png = diag.save_condensed_tree_plot(res, str(DIAG_DIR / f'condensed_tree_{name}_{rid}.png'))
    scatter_png = diag.save_umap_scatter(res, str(DIAG_DIR / f'umap_scatter_{name}_{rid}.png'))
    if tree_png is None:
        print(f"[{name}] (matplotlib not installed — condensed-tree table written, plot skipped)")

# Per-config cluster composition: distinct bills per cluster is the artifact
# check. single_bill=True means a cluster is one bill's provisions, not a
# cross-bill legal concept.
for name, res in results.items():
    print(f"\n=== config {name} ({res.config.run_id()}) — cluster composition ===")
    comp = pd.DataFrame(res.cluster_composition())
    if len(comp):
        display(comp[['cluster_id', 'size', 'n_bills', 'single_bill', 'mean_prob']])
    else:
        print("  (no clusters — all noise)")

# Full per-bullet assignment (with bill_id) for inspection:
for name, res in results.items():
    print(f"\n=== config {name} — per-bullet (head) ===")
    display(pd.DataFrame(res.diagnostic_table())
            .sort_values(['cluster_id', 'bill_id']).head(20))


resB = results['E']
tbl = pd.DataFrame(resB.diagnostic_table())
for cid in [12, 3, 8, 6]:   # the 4-5 bill clusters
    print(f"\n=== cluster {cid} ===")
    for _, r in tbl[tbl.cluster_id == cid].sort_values('bill_id').iterrows():
        print(f"  [{r['bill_id']}] {r['bullet']}")

/home/nick/Documents/projects/lawsofisrael/.venv/lib/python3.12/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[A] run_id=umap15x5_mcs3_leaf_seed42 n_clusters=24 noise=8% cross_bill=6 single_bill=18
[A] (matplotlib not installed — condensed-tree table written, plot skipped)

/home/nick/Documents/projects/lawsofisrael/.venv/lib/python3.12/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[B] run_id=umap15x5_mcs5_eom_seed42 n_clusters=14 noise=15% cross_bill=8 single_bill=6
[B] (matplotlib not installed — condensed-tree table written, plot skipped)

/home/nick/Documents/projects/lawsofisrael/.venv/lib/python3.12/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[C] run_id=umap15x5_mcs5_leaf_seed42 n_clusters=15 noise=15% cross_bill=8 single_bill=7
[C] (matplotlib not installed — condensed-tree table written, plot skipped)

/home/nick/Documents/projects/lawsofisrael/.venv/lib/python3.12/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[D] run_id=umap15x5_mcs7_eom_seed42 n_clusters=7 noise=19% cross_bill=7 single_bill=0
[D] (matplotlib not installed — condensed-tree table written, plot skipped)

/home/nick/Documents/projects/lawsofisrael/.venv/lib/python3.12/site-packages/umap/umap_.py:1952: UserWarning: n_jobs value 1 overridden to 1 by setting random_state. Use no seed for parallelism.
  warn(

[E] run_id=umap15x5_mcs4_leaf_seed42 n_clusters=21 noise=5% cross_bill=8 single_bill=13
[E] (matplotlib not installed — condensed-tree table written, plot skipped)

=== config A (umap15x5_mcs3_leaf_seed42) — cluster composition ===

    cluster_id  size  n_bills  single_bill  mean_prob
0           22     9        5        False   0.792627
1           14    13        3        False   0.622214
2           19     9        2        False   0.854099
3           15     8        2        False   0.824107
4           21     8        2        False   0.827918
5           11     8        2        False   0.856421
6            5     7        1         True   0.879734
7           20     7        1         True   0.923746
8            1     7        1         True   0.953333
9            3     7        1         True   0.903741
10           0     7        1         True   0.933435
11           7     7        1         True   0.836438
12           9     7        1         True   0.726010
13           4     6        1         True   0.866935
14           6     5        1         True   0.963657
15          17     5        1         True   0.957490
16           2     5        1         True   0.956000
17          10     5        1         True   0.898976
18           8     5        1         True   0.964065
19          18     5        1         True   0.858875
20          12     5        1         True   0.948950
21          23     4        1         True   1.000000
22          16     4        1         True   0.952521
23          13     4        1         True   1.000000

=== config B (umap15x5_mcs5_eom_seed42) — cluster composition ===

    cluster_id  size  n_bills  single_bill  mean_prob
0           12    10        5        False   0.886536
1            3    20        4        False   0.997945
2            8    18        4        False   0.691700
3            6    18        4        False   0.765624
4            0    12        2        False   0.856406
5           13     9        2        False   0.916780
6            7     8        2        False   0.947504
7           11     8        2        False   0.875875
8            4     7        1         True   0.975434
9           10     7        1         True   0.971710
10           2     7        1         True   0.951961
11           1     7        1         True   0.974752
12           5     7        1         True   0.925718
13           9     7        1         True   0.940858

=== config C (umap15x5_mcs5_leaf_seed42) — cluster composition ===

    cluster_id  size  n_bills  single_bill  mean_prob
0           13    10        5        False   0.886536
1            9    18        4        False   0.691700
2            7    18        4        False   0.765624
3            4    13        3        False   0.874327
4            0    12        2        False   0.856406
5           14     9        2        False   0.916780
6            8     8        2        False   0.947504
7           12     8        2        False   0.875875
8            3     7        1         True   0.975434
9           11     7        1         True   0.971710
10           2     7        1         True   0.951961
11           1     7        1         True   0.974752
12           6     7        1         True   0.925718
13          10     7        1         True   0.940858
14           5     6        1         True   0.997828

=== config D (umap15x5_mcs7_eom_seed42) — cluster composition ===

   cluster_id  size  n_bills  single_bill  mean_prob
0           0    42        8        False   0.520039
1           4    25        7        False   0.921581
2           6    20        4        False   0.791668
3           2    20        4        False   0.817318
4           3    11        3        False   0.934836
5           1    12        2        False   0.963692
6           5     8        2        False   1.000000

=== config E (umap15x5_mcs4_leaf_seed42) — cluster composition ===

    cluster_id  size  n_bills  single_bill  mean_prob
0           20    11        5        False   0.739891
1           10    18        4        False   0.588378
2            6    13        3        False   0.925361
3           19     9        2        False   0.903898
4           12     8        2        False   0.894150
5           15     8        2        False   0.859322
6           17     8        2        False   0.912176
7            5     7        2        False   0.839649
8            7     7        1         True   0.878774
9           14     7        1         True   0.956275
10           2     7        1         True   0.993225
11           1     7        1         True   0.933477
12           0     7        1         True   0.955085
13           9     7        1         True   0.867162
14          11     7        1         True   0.904128
15           4     5        1         True   1.000000
16           3     5        1         True   1.000000
17          16     5        1         True   1.000000
18           8     5        1         True   1.000000
19          13     5        1         True   1.000000
20          18     5        1         True   1.000000

=== config A — per-bullet (head) ===

,bullet_row_id,bill_id,bullet,cluster_id,membership_prob,outlier_score,umap_x,umap_y
145,1046571:0000#b002,1046571,הקניית סמכויות אכיפה לשוטר לשם אכיפת הוראות הה...,-1,0.000000,0.758091,0.795540,2.064509
87,2197936:0000#b000,2197936,החלפת המילים עשרים ושמונה בשלושים ושלושים וארב...,-1,0.000000,0.823571,1.040890,3.817379
88,2197936:0000#b001,2197936,החלפת המילים עשרים ושלוש בשלושים ושלוש בסעיף ק...,-1,0.000000,0.814129,0.941608,3.752281
85,2198907:0000#b000,2198907,הגדרת לימוד התורה כערך יסוד במורשת העם היהודי,-1,0.000000,0.433346,3.588107,1.964453
86,2198907:0000#b001,2198907,הכרזה על לימוד התורה כערך יסוד במדינת ישראל,-1,0.000000,0.621115,3.517259,1.870243
64,2200908:0000#b003,2200908,השתתפות תקציבית של המדינה במרכז בהתאם לחוק התק...,-1,0.000000,0.314080,3.461127,2.393147
41,2202055:0000#b000,2202055,הוספת דודנם של בני המשפחה להגדרת בן משפחה בחוק...,-1,0.000000,0.755909,0.572808,3.300297
42,2202055:0000#b001,2202055,החלת תיקון סעיף 18א על תביעות שטרם התיישנו ערב...,-1,0.000000,0.777760,0.615558,3.199354
37,2220910:0000#b000,2220910,תיקון סעיף 15 במסגרת הוראת שעה לגבי יוצא צבא ב...,-1,0.000000,0.618720,0.524867,3.660990
39,2220910:0000#b002,2220910,קביעת דמי קיום בגובה כפל דמי הקיום הקבועים לפי...,-1,0.000000,0.846084,1.610468,3.235729
40,2220910:0000#b003,2220910,קביעת דמי קיום בשיעור 175% מדמי הקיום הקבועים ...,-1,0.000000,0.852374,1.588100,3.248947
71,2237751:0000#b005,2237751,הטלת האחריות על ביצוע החוק על שر המורשת,-1,0.000000,0.436017,3.733052,1.899055
72,2237751:0000#b006,2237751,הסמכת שر המורשת להיות ממונה על ביצוע חוק זה,-1,0.000000,0.478010,3.789560,1.840473
107,2225412:0000#b000,2225412,קביעת שר הפנים שמסתנן תומך ממשל יוצרת חזקה להי...,0,1.000000,0.000000,2.445677,4.192976
108,2225412:0000#b001,2225412,חובת שר הפנים לבטל מיד רישיון ישיבה של מסתנן ש...,0,1.000000,0.000000,2.413768,4.218206
109,2225412:0000#b002,2225412,חובת שר הפנים להרחיק מישראל מסתנן שרישיון ישיב...,0,1.000000,0.000000,2.476288,4.149731
110,2225412:0000#b003,2225412,חובת שר הפנים לבטל רישיון ישיבה של מסתנן שהורש...,0,1.000000,0.000000,2.372928,4.260623
111,2225412:0000#b004,2225412,חובת שר הפנים להרחיק מישראל מסתנן שהורשע בעביר...,0,0.852709,0.147291,2.362059,4.285433
112,2225412:0000#b005,2225412,חובת שר הפנים לדווח אחת לשנה לוועדת הפנים על י...,0,0.722763,0.277237,2.476087,4.028959
113,2225412:0000#b006,2225412,דיווח שנתי של שר הפנים חל על הוראות הביטול והה...,0,0.958571,0.041429,2.506747,4.109888

=== config B — per-bullet (head) ===

,bullet_row_id,bill_id,bullet,cluster_id,membership_prob,outlier_score,umap_x,umap_y
128,1043724:0000#b000,1043724,הגדרת בעל מלאי כמי שהחזיק כמויות סף בתוספת,-1,0.0,0.819101,1.720503,2.232299
129,1043724:0000#b001,1043724,חובת דיווח חודשי של בעל מלאי על כמויות ומיקום,-1,0.0,0.820558,1.711365,2.239821
130,1043724:0000#b002,1043724,הסמכת המנהל להטיל עיצום כספי על הפרת הוראות החוק,-1,0.0,0.805372,1.658882,2.201092
131,1043724:0000#b003,1043724,מינוי מנהל לעניין החוק וממלא מקום מקרב עובדי ה...,-1,0.0,0.834582,1.788038,2.285189
132,1043724:0000#b004,1043724,דחיית יום התחילה בצו באישור ועדת הכלכלה,-1,0.0,0.834260,1.771056,2.296621
133,1046091:0000#b000,1046091,הגדרת מטרת החוק כשיקום אזורי נזק מלחמה באמצעות...,-1,0.0,0.697179,2.935529,3.334399
134,1046091:0000#b001,1046091,הסמכת הממשלה או ועדת שרים להכריז על אזור לשיקו...,-1,0.0,0.696547,2.954823,3.288694
135,1046091:0000#b002,1046091,קביעת שיעור היטל שיקום מופחת בגובה רבע מההשבחה...,-1,0.0,0.663958,2.902335,3.301525
136,1046091:0000#b003,1046091,חובת יזם שיקום לרכוש זכויות מקרקעין מבעל דירה ...,-1,0.0,0.763955,3.071010,3.393550
137,1046091:0000#b004,1046091,רשות ליזם שיקום לבקש ממנהל מס רכוש סיוע במימון...,-1,0.0,0.732828,3.012818,3.358321
87,2197936:0000#b000,2197936,החלפת המילים עשרים ושמונה בשלושים ושלושים וארב...,-1,0.0,0.791591,1.040890,3.817379
88,2197936:0000#b001,2197936,החלפת המילים עשרים ושלוש בשלושים ושלוש בסעיף ק...,-1,0.0,0.793478,0.941608,3.752281
41,2202055:0000#b000,2202055,הוספת דודנם של בני המשפחה להגדרת בן משפחה בחוק...,-1,0.0,0.625199,0.572808,3.300297
42,2202055:0000#b001,2202055,החלת תיקון סעיף 18א על תביעות שטרם התיישנו ערב...,-1,0.0,0.690106,0.615558,3.199354
39,2220910:0000#b002,2220910,קביעת דמי קיום בגובה כפל דמי הקיום הקבועים לפי...,-1,0.0,0.796433,1.610468,3.235729
40,2220910:0000#b003,2220910,קביעת דמי קיום בשיעור 175% מדמי הקיום הקבועים ...,-1,0.0,0.803325,1.588100,3.248947
4,2229019:0000#b000,2229019,תיקון חוק הליכי חקירה והעדה מס' 5 לאנשים עם מו...,-1,0.0,0.578035,-0.022502,3.234670
6,2229019:0000#b002,2229019,התרת זכות לנוכחות עורך דין במהלך חקירה משטרתית,-1,0.0,0.690153,-0.175177,3.095230
7,2229019:0000#b003,2229019,התרת התחלת חקירה ללא המתנה להגעת עורך דין,-1,0.0,0.602331,-0.281108,3.149827
8,2229019:0000#b004,2229019,הסדרת התנהלותו של עורך דין הנוכח בפועל בחקירה,-1,0.0,0.679011,-0.104808,3.104239

=== config C — per-bullet (head) ===

,bullet_row_id,bill_id,bullet,cluster_id,membership_prob,outlier_score,umap_x,umap_y
128,1043724:0000#b000,1043724,הגדרת בעל מלאי כמי שהחזיק כמויות סף בתוספת,-1,0.0,0.819101,1.720503,2.232299
129,1043724:0000#b001,1043724,חובת דיווח חודשי של בעל מלאי על כמויות ומיקום,-1,0.0,0.820558,1.711365,2.239821
130,1043724:0000#b002,1043724,הסמכת המנהל להטיל עיצום כספי על הפרת הוראות החוק,-1,0.0,0.805372,1.658882,2.201092
131,1043724:0000#b003,1043724,מינוי מנהל לעניין החוק וממלא מקום מקרב עובדי ה...,-1,0.0,0.834582,1.788038,2.285189
132,1043724:0000#b004,1043724,דחיית יום התחילה בצו באישור ועדת הכלכלה,-1,0.0,0.834260,1.771056,2.296621
133,1046091:0000#b000,1046091,הגדרת מטרת החוק כשיקום אזורי נזק מלחמה באמצעות...,-1,0.0,0.697179,2.935529,3.334399
134,1046091:0000#b001,1046091,הסמכת הממשלה או ועדת שרים להכריז על אזור לשיקו...,-1,0.0,0.696547,2.954823,3.288694
135,1046091:0000#b002,1046091,קביעת שיעור היטל שיקום מופחת בגובה רבע מההשבחה...,-1,0.0,0.663958,2.902335,3.301525
136,1046091:0000#b003,1046091,חובת יזם שיקום לרכוש זכויות מקרקעין מבעל דירה ...,-1,0.0,0.763955,3.071010,3.393550
137,1046091:0000#b004,1046091,רשות ליזם שיקום לבקש ממנהל מס רכוש סיוע במימון...,-1,0.0,0.732828,3.012818,3.358321
87,2197936:0000#b000,2197936,החלפת המילים עשרים ושמונה בשלושים ושלושים וארב...,-1,0.0,0.791591,1.040890,3.817379
88,2197936:0000#b001,2197936,החלפת המילים עשרים ושלוש בשלושים ושלוש בסעיף ק...,-1,0.0,0.793478,0.941608,3.752281
64,2200908:0000#b003,2200908,השתתפות תקציבית של המדינה במרכז בהתאם לחוק התק...,-1,0.0,0.430813,3.461127,2.393147
41,2202055:0000#b000,2202055,הוספת דודנם של בני המשפחה להגדרת בן משפחה בחוק...,-1,0.0,0.625199,0.572808,3.300297
42,2202055:0000#b001,2202055,החלת תיקון סעיף 18א על תביעות שטרם התיישנו ערב...,-1,0.0,0.690106,0.615558,3.199354
39,2220910:0000#b002,2220910,קביעת דמי קיום בגובה כפל דמי הקיום הקבועים לפי...,-1,0.0,0.796433,1.610468,3.235729
40,2220910:0000#b003,2220910,קביעת דמי קיום בשיעור 175% מדמי הקיום הקבועים ...,-1,0.0,0.803325,1.588100,3.248947
4,2229019:0000#b000,2229019,תיקון חוק הליכי חקירה והעדה מס' 5 לאנשים עם מו...,-1,0.0,0.578035,-0.022502,3.234670
6,2229019:0000#b002,2229019,התרת זכות לנוכחות עורך דין במהלך חקירה משטרתית,-1,0.0,0.690153,-0.175177,3.095230
7,2229019:0000#b003,2229019,התרת התחלת חקירה ללא המתנה להגעת עורך דין,-1,0.0,0.602331,-0.281108,3.149827

=== config D — per-bullet (head) ===

,bullet_row_id,bill_id,bullet,cluster_id,membership_prob,outlier_score,umap_x,umap_y
154,1046680:0000#b000,1046680,תיקון חוק התכנון והבנייה במסגרת תיקון מס' 164,-1,0.0,0.586783,0.884926,3.081514
156,1046680:0000#b002,1046680,תיקון חוק הרשות הארצית לכבאות והצלה במס' 13,-1,0.0,0.608642,0.819279,3.059726
87,2197936:0000#b000,2197936,החלפת המילים עשרים ושמונה בשלושים ושלושים וארב...,-1,0.0,0.541120,1.040890,3.817379
88,2197936:0000#b001,2197936,החלפת המילים עשרים ושלוש בשלושים ושלוש בסעיף ק...,-1,0.0,0.571941,0.941608,3.752281
96,2197937:0000#b000,2197937,הקמת מחלקה לחקירת שוטרים במשרד המשפטים בידי שר...,-1,0.0,0.626324,0.085992,2.822776
97,2197937:0000#b001,2197937,קביעת כשירות מנהל המחלקה לבעל ניסיון פלילי ושו...,-1,0.0,0.635751,0.054991,2.848231
98,2197937:0000#b002,2197937,הגשת כתבי אישום בעבירות שנחקרו במחלקה בידי תוב...,-1,0.0,0.634417,0.030661,2.862739
99,2197937:0000#b003,2197937,הכרעה במחלוקת בין המחלקה לגוף חוקר בידי הממונה...,-1,0.0,0.620146,0.085570,2.814135
100,2197937:0000#b004,2197937,העברת תיקי חקירה ותביעה בין המחלקה לגופים אחרי...,-1,0.0,0.644849,-0.001490,2.892823
114,2220439:0000#b000,2220439,קידום מתן סיוע והסדרת זכויות בני משפחה של נעדרים,-1,0.0,0.674854,2.416214,2.526361
115,2220439:0000#b001,2220439,מינוי ועדה לתכלול מעני רשויות המדינה לבני משפח...,-1,0.0,0.677972,2.483205,2.494807
116,2220439:0000#b002,2220439,גיבוש נהלים להסדרי עבודה קבועים בין משרדי הממש...,-1,0.0,0.680861,2.575011,2.390716
117,2220439:0000#b003,2220439,בחינת מקרים פרטניים להפקת לקחים ותיקון ליקויים...,-1,0.0,0.674414,2.517736,2.451762
118,2220439:0000#b004,2220439,"חובת משטרת ישראל וצה""ל להודיע לוועדה על נעדרים...",-1,0.0,0.679945,2.556416,2.400196
119,2220439:0000#b005,2220439,הגבלת חובת הודעת גורמי הביטחון לוועדה כך שלא ת...,-1,0.0,0.674781,2.663158,2.335440
120,2220439:0000#b006,2220439,חובת משטרה ליידע בן משפחה של נעדר על אפשרות פנ...,-1,0.0,0.668569,2.492132,2.457748
39,2220910:0000#b002,2220910,קביעת דמי קיום בגובה כפל דמי הקיום הקבועים לפי...,-1,0.0,0.600479,1.610468,3.235729
40,2220910:0000#b003,2220910,קביעת דמי קיום בשיעור 175% מדמי הקיום הקבועים ...,-1,0.0,0.601710,1.588100,3.248947
107,2225412:0000#b000,2225412,קביעת שר הפנים שמסתנן תומך ממשל יוצרת חזקה להי...,-1,0.0,0.827502,2.445677,4.192976
108,2225412:0000#b001,2225412,חובת שר הפנים לבטל מיד רישיון ישיבה של מסתנן ש...,-1,0.0,0.823032,2.413768,4.218206

=== config E — per-bullet (head) ===

,bullet_row_id,bill_id,bullet,cluster_id,membership_prob,outlier_score,umap_x,umap_y
87,2197936:0000#b000,2197936,החלפת המילים עשרים ושמונה בשלושים ושלושים וארב...,-1,0.000000,0.822227,1.040890,3.817379
88,2197936:0000#b001,2197936,החלפת המילים עשרים ושלוש בשלושים ושלוש בסעיף ק...,-1,0.000000,0.821975,0.941608,3.752281
41,2202055:0000#b000,2202055,הוספת דודנם של בני המשפחה להגדרת בן משפחה בחוק...,-1,0.000000,0.704302,0.572808,3.300297
42,2202055:0000#b001,2202055,החלת תיקון סעיף 18א על תביעות שטרם התיישנו ערב...,-1,0.000000,0.758144,0.615558,3.199354
39,2220910:0000#b002,2220910,קביעת דמי קיום בגובה כפל דמי הקיום הקבועים לפי...,-1,0.000000,0.831490,1.610468,3.235729
40,2220910:0000#b003,2220910,קביעת דמי קיום בשיעור 175% מדמי הקיום הקבועים ...,-1,0.000000,0.837553,1.588100,3.248947
6,2229019:0000#b002,2229019,התרת זכות לנוכחות עורך דין במהלך חקירה משטרתית,-1,0.000000,0.653128,-0.175177,3.095230
7,2229019:0000#b003,2229019,התרת התחלת חקירה ללא המתנה להגעת עורך דין,-1,0.000000,0.641487,-0.281108,3.149827
8,2229019:0000#b004,2229019,הסדרת התנהלותו של עורך דין הנוכח בפועל בחקירה,-1,0.000000,0.625074,-0.104808,3.104239
107,2225412:0000#b000,2225412,קביעת שר הפנים שמסתנן תומך ממשל יוצרת חזקה להי...,0,1.000000,0.000000,2.445677,4.192976
108,2225412:0000#b001,2225412,חובת שר הפנים לבטל מיד רישיון ישיבה של מסתנן ש...,0,1.000000,0.000000,2.413768,4.218206
109,2225412:0000#b002,2225412,חובת שר הפנים להרחיק מישראל מסתנן שרישיון ישיב...,0,1.000000,0.000000,2.476288,4.149731
110,2225412:0000#b003,2225412,חובת שר הפנים לבטל רישיון ישיבה של מסתנן שהורש...,0,0.983850,0.016150,2.372928,4.260623
111,2225412:0000#b004,2225412,חובת שר הפנים להרחיק מישראל מסתנן שהורשע בעביר...,0,0.859690,0.140310,2.362059,4.285433
112,2225412:0000#b005,2225412,חובת שר הפנים לדווח אחת לשנה לוועדת הפנים על י...,0,0.842053,0.157947,2.476087,4.028959
113,2225412:0000#b006,2225412,דיווח שנתי של שר הפנים חל על הוראות הביטול והה...,0,1.000000,0.000000,2.506747,4.109888
54,2219317:0000#b000,2219317,חובת עוסק להקליט שיחות קוליות בעסקאות תוספת תש...,1,1.000000,0.000000,0.160784,0.692746
55,2219317:0000#b001,2219317,הקלטת שיחות טלפון גם בתקשורת אלקטרונית ללא נוכחות,1,0.909076,0.090924,0.102020,0.753784
56,2219317:0000#b002,2219317,הכללת שיחות יזומות מצד הצרכן במסגרת חובת ההקלטה,1,0.780984,0.219016,0.255711,0.616338
57,2219317:0000#b003,2219317,חובת עוסק ליידע את הצרכן בתחילת השיחה על ההקלטה,1,1.000000,0.000000,0.189763,0.682852

=== cluster 12 ===
  [2199298] קביעת עונש מוות למחבלים שביצעו פיגועי טרור רצחניים כאמצעי מאבק
  [2199298] הטלת עונש מוות על תושב האזור הגורם בכוונה למות אדם במעשה טרור
  [2199298] ביצוע עונש מוות שגזר בית משפט צבאי בידי שירות בתי הסוהר
  [2199298] ביצוע גזר דין מוות בעבירות ביטחון בתוך 90 ימים מהיותו לחלוט
  [2199298] הטלת עונש מיתה או מאסר עולם על גרימת מוות בכוונה לשלוילת קיומה של מדינת ישראל
  [2201009] קביעת עונש מאסר חמש שנים בשל עבירה בחלק מהותי בנשק
  [2201009] קביעת עונש מאסר שלוש שנים בשל עבירה בחלק נשק שאינו מהותי
  [2201009] חובת בית המשפט להורות על חילוט רכוש לאוצר המדינה בהרשעה

=== cluster 3 ===
  [2216066] תיקון חוק הרשות השנייה לטלוויזיה ורדיו במסגרת תיקון מספר 50
  [2216066] הסדרת נושא תיקון סעיף 34 הנוגע לרישוי שידורים
  [2216066] קביעת הוראות ספציפיות לעניין רישוי שידורי רדיו אנלוגי
  [2216066] מתן חובה לפרסום מכרז ראשון למתן רישיון לשידורי רדיו אנלוגי
  [2216066] הכללת הוראות מעבר במסגרת התיקון לחוק

=== cluster 8 ===
  [1043724] הגדרת בעל מלאי כמי שהחזיק כמויות סף בתוספת
  [1043724] חובת דיווח חודשי של בעל מלאי על כמויות ומיקום
  [1043724] הסמכת המנהל להטיל עיצום כספי על הפרת הוראות החוק
  [1043724] מינוי מנהל לעניין החוק וממלא מקום מקרב עובדי המשרד
  [1043724] דחיית יום התחילה בצו באישור ועדת הכלכלה

=== cluster 6 ===
  [2198907] הגדרת לימוד התורה כערך יסוד במורשת העם היהודי
  [2200908] הקמת מרכז גולדה מאיר לחקר החברה בישראל להנצחת זכרה
  [2200908] מינוי מועצה בת תשעה חברים למרכז בידי השר
  [2200908] קיום יום הנצחה שנתי לזכר גולדה מאיר ביום ח' בכסלו
  [2200908] השתתפות תקציבית של המדינה במרכז בהתאם לחוק התקציב השנתי
  [2200908] העמדת סכום השתתפות מינימלי של 7,194,000 שקלים חדשים בשנה החל משנת 2026
  [2237751] קיום יום לציון מורשת יהדות מרוקו וצפון אפריקה מדי שנה ביום כ"ג בטבת
  [2237751] ציון יום מורשת יהדות מרוקו וצפון אפריקה ביום טביעתה של ספינת "אגוז"
  [2237751] ציון ע과יית היהודים מקהילות מרוקו וצפון אפריקה לישראל במסגרת יום הציון
  [2237751] הנצחת זכרם של הנספים בדרך לישראל במסגרת יום הציון
  [2237751] קיום דרכי ציון שונות ליום מורשת יהדות מרוקו וצפון אפריקה בין השאר
  [2237751] הטלת האחריות על ביצוע החוק על שر המורשת
  [2237751] הסמכת שر המורשת להיות ממונה על ביצוע חוק זה

## 8. Decision point — choose ONE configuration deliberately

**This is the selection mechanism.** Having inspected nearest neighbors and the
clustering diagnostics above, set `CHOSEN_CONFIG` to the key of the configuration
you judge appropriate — or leave it `None` to stay in an exploratory, *no-label*
state. Nothing is synthesized while `CHOSEN_CONFIG is None`.

In [19]:
CHOSEN_CONFIG = 'E'   # e.g. 'A' — set only after inspecting the diagnostics above.

if CHOSEN_CONFIG is None:
    chosen_result = None
    print("Exploratory state: no configuration chosen -> NO labels will be synthesized.")
    print("Inspect the diagnostics above, then set CHOSEN_CONFIG to a config key and re-run from here.")
else:
    chosen_result = results[CHOSEN_CONFIG]
    # Guard: the chosen result must match the bullets we actually inspected.
    diag.guard_selection(chosen_result, expected_bullet_prompt_hash=SUMMARIZE_PROMPT_HASH)
    print(f"Chosen config {CHOSEN_CONFIG}: {chosen_result.config.run_id()} "
          f"({chosen_result.n_clusters()} clusters, noise {chosen_result.noise_ratio():.0%})")

Chosen config E: umap15x5_mcs4_leaf_seed42 (21 clusters, noise 5%)

## 9. Synthesize labels from the chosen clustering (no scoring)

`diag.synthesize_from_result` re-guards against a mismatched bullet corpus,
builds the per-cluster input from the **chosen** result only, synthesizes with
the condition-faithful prompt, reviews, and selects. The pipeline ends here:
there is deliberately no `session.score`.

In [20]:
if chosen_result is None:
    print("No configuration chosen — skipping synthesis (exploratory state).")
    concepts_table = []
else:
    with auto_confirm():
        selected_ids = await diag.synthesize_from_result(
            session, chosen_result, custom_prompts, GEN_PARAMS,
            expected_bullet_prompt_hash=SUMMARIZE_PROMPT_HASH,
            max_concepts=MAX_CONCEPTS,
        )
    v2_export.assert_no_scoring(session)  # guard: v2.1 must not score
    concepts_table = v2_export.build_concepts_table(session)
    print(f"Selected {len(selected_ids)} labels")
pd.DataFrame(concepts_table)

Selected 30 labels

,concept_id,label,criterion,rep_chunk_ids
0,963593f4-0e3c-43db-9faf-497f22a7049b,"הארכת תוקף, תיקון או החלת הוראת שעה לגבי בתי ס...","האם הטקסט עוסק בהארכת תוקף, תיקון או קביעה של ...","[1057303:0000, 1057405:0000]"
1,a4cbfc70-ad0e-409a-8de2-90fee4909ce5,תיקון חקיקה או הארכת תוקף הוראת שעה בענייני קט...,האם הטקסט עוסק בתיקון חוק או בהוראת שעה הנוגעת...,[2229019:0000]
2,356272b8-d263-4fd1-ac82-73a628251be7,הארכת תוקף או תיקון הוראת שעה וסעיפים הנוגעים ...,"האם הטקסט עוסק בהארכת תוקף, תחולה או תיקון של ...","[1057200:0000, 2220910:0000]"
3,fe852204-3251-4052-a0a3-494a893ef6be,קביעת הוראות מיוחדות והיערכות מיוחדת לבחירות ב...,האם הטקסט קובע הוראות מיוחדות או מסמיך גורמים ...,[2244462:0000]
4,d3ed196a-64df-46a1-90b9-b16b72723a0d,הסדרת זכות הצבעה בקלפי ייעודית או נגישה לבעלי ...,האם הטקסט מקנה זכות הצבעה ומסדיר את האפשרות לה...,[2244462:0000]
5,c230e000-d4ef-465e-9312-afa54e65a1e2,חובת צירוף גילוי ברור ובולט על תעמולת בחירות ש...,האם הטקסט מטיל חובה לצרף גילוי ברור ובולט על ח...,[2244462:0000]
6,e7af7a31-a2bf-486b-a397-f9fd437a8c62,הקמת הרשות לתקשורת משודרת כגוף חדש וכאשכול משפ...,האם הטקסט קובע את הקמתה של הרשות לתקשורת משודר...,[1042100:0000]
7,eb03bd33-d12e-4df3-9016-8eaead86be3b,איסור עיסוק או פעילות ללא רישיון או היתר כנדרש,האם הטקסט קובע איסור מפורש על אדם או גוף לעסוק...,"[1046571:0000, 2204244:0000]"
8,7a5cfc75-55a9-47c2-b0b3-790416ec5e33,הסמכת רשויות או גורמים לבצע פעולות ואכיפה לפי חוק,האם הטקסט מעניק סמכות פעולה או אכיפה לגוף מוסמ...,"[1046571:0000, 1046237:0000]"
9,7d11e64c-e4a6-46b8-8978-5e8d2854c518,תוקף משפטי של ייפוי כוח לתאגיד או לעסקה ללא ער...,האם הטקסט קובע כי ייפוי כוח שניתן לתאגיד או לב...,[2232915:0000]
10,78d608e5-b444-41dc-8a57-1c6dfb57b012,חובת עוסק להקליט שיחות קוליות ולשמור את ההקלטות,האם הטקסט קובע חובת הקלטה של שיחות או חובת שמי...,[2219317:0000]
11,e8868f84-1f15-46d0-86b3-2cf06172a831,חובת יידוע הצרצר על הקלטת השיחה ועל זכותו לקבלתה,האם הטקסט מחייב ליידע את הצרכן בתחילת השיחה על...,[2219317:0000]
12,98611dfe-549e-4c18-a713-5060cd0f9af0,קיום יום זיכרון או ציון מורשת שנתי וקבוע בחוק,"האם הטקסט קובע חובה או הוראה לקיים יום זיכרון,...","[2200908:0000, 2237751:0000]"
13,8d5a7d04-669f-432e-8b94-f0a418000db5,הטלת אחריות והסמכת שר ממונה על ביצוע הוראות החוק,האם הטקסט מסמיך שר מסוים או מטיל עליו את האחרי...,[2237751:0000]
14,ad98e6dd-b00b-44f9-860d-d73a7988851f,התרת חיפוש ללא צו במקום או בבית בהוראת שעה,האם הטקסט עוסק בהתרת או בהגבלת חיפוש משטרתי לל...,"[1057200:0000, 2201009:0000]"
15,8f5db1be-29a8-4fa4-a70a-3d9d4d95ac1e,התניית חיפוש משטרתי באישור קצין בדרגת רב־פקד ו...,האם הטקסט דורש אישור קצין משטרה או תיעוד בכתב ...,[2201009:0000]
16,715cd8a3-9a8e-44c2-8236-13fc56d2a9e4,תיקון חוק הרשות השנייה לטלוויזיה ורדיו לרבות ה...,האם הטקסט עוסק בתיקון חוק הרשות השנייה לטלוויז...,[2216066:0000]
17,04d9683c-40c6-41ec-b4f0-8805f97669e7,"הכרה חוקית, קביעת הסדרים ופעילות באמצעות האקדמ...","האם הטקסט קובע הסדרים, פעילות או הכרה הקשורים ...",[2229413:0000]
18,e2a6ccef-0e71-4ede-b41c-4d29a6adeaa4,קביעת עונשי מאסור בשל עבירות נשק או חובת חילוט...,האם התמצית עוסקת בקביעת עונשי מאסור לתקופות קצ...,[2201009:0000]
19,3c93baa2-053e-478e-a025-be73f13157ee,הטלת עונש מוות או מאסור עולם על מעשי טרור וגרמ...,"האם התמצית עוסקת בהטלת עונש מוות, גזר דין מוות...",[2199298:0000]
20,58f6139f-beb3-4a1d-8161-f2a1b61b70c3,הקמת מחלקה לחקירת שוטרים במשרד המשפטים בידי שר...,האם הטקסט קובע את סמכותו של ששר המשפטים להקים ...,[2197937:0000]
21,4cd27b01-a944-4eee-9edd-57b4cf99c5d7,חובת שר הפנים לבטל רישיון ישיבה ולהרחיק מסתנן ...,האם הטקסט קובע את חובתו של שר הפנים לבטל את רי...,[2225412:0000]
22,330ab269-acf3-4980-a526-7f351f17cfb5,חובת גורמי הביטחון ומשטרת ישראל למסור מידע על ...,"האם הטקסט קובע חובה על משטרת ישראל וצה""ל להודי...",[2220439:0000]
23,b5cdbc6b-bb9d-4542-b027-c37f8e5297bb,חובת דיווח חודשי של בעל מלאי על כמויות ומקום,האם הטקסט קובע חובה על בעל מלאי לדווח מדי חודש...,[1043724:0000]
24,85c36777-a586-4f75-a7c7-62f5601592d6,הסמכת הממשלה או ועדת שרים להכריז על אזור לשיקו...,האם הטקסט עוסק בהסמכת הממשלה או ועדת שרים להכר...,[1046091:0000]
25,9bbbbcf2-c8db-4b27-8a7f-67ee08ed6787,חובת יזם שיקום לרכוש זכויות מקרקעין מבעל דירה ...,האם הטקסט קובע את חובתו של יזם שיקום לרכוש זכו...,[1046091:0000]
26,7d0c81eb-e354-43a6-8fca-b89f06e4c37f,"אישור תקציב המדינה, מכסת משרות כוח אדם וחלוקת ...","האם הטקסט עוסק באישור תקציב המדינה, מכסת משרות...",[1046679:0000]
27,8e2388a1-4232-47e7-87c4-5f349d8aeb23,התרת סמכות לבית דין רבני או שרעי לדון כבורור ב...,האם הטקסט עוסק בהתרת או התניית סמכות של בית די...,[2197901:0000]
28,bbf7d26c-3410-4b48-ac06-84cdb1214586,זכויות נפגעי הלם קרב,"האם הטקסט עוסק במתן טיפול מותאם, הבטחת זכויות ...","[2218723:0000, 2218723:0000]"
29,983bd2da-7756-484c-be25-05458e42c197,חובת דיווח פרלמנטרי,האם הטקסט קובע חובת דיווח מטעם שר בממשלה לוועד...,"[2218723:0000, 2225412:0000]"

## 10. Run manifest (reproducibility)

In [21]:
clustering_info = None
artifact_paths = {
    'bullets': str((DIAG_DIR / 'bullets_v2.parquet').relative_to(ROOT)),
    'nearest_neighbors': str((DIAG_DIR / 'nearest_neighbors_v2.parquet').relative_to(ROOT)),
}
if chosen_result is not None:
    rid = chosen_result.config.run_id()
    clustering_info = diag.clustering_manifest_entry(chosen_result)
    clustering_info['chosen_config_key'] = CHOSEN_CONFIG
    artifact_paths['condensed_tree'] = f'notebooks/outputs/diagnostics/condensed_tree_{CHOSEN_CONFIG}_{rid}.parquet'

manifest = v2_export.build_run_manifest(
    corpus_id=CORPUS_ID,
    n_bills=N_BILLS,
    n_chunks=len(chunks_df),
    chat_model=CHAT_MODEL,
    embed_model=EMBED_MODEL,
    lloom_version=version('text_lloom'),
    gen_params=GEN_PARAMS,
    prompt_info=PROMPT_INFO,
    timestamp=datetime.now(timezone.utc).isoformat(),
    experiment='lloom_v2.1_semantic_diagnostics',
    bullet_accounting=ACCOUNTING,
    nearest_neighbor_info={
        'k': NN_K, 'metric': 'cosine',
        'embed_backend': embed_backend_id,
        'instruction': EMBED_INSTRUCTION,
        'domain_context': bool(USE_DOMAIN_CONTEXT),
    },
    clustering_info=clustering_info,
    artifact_paths=artifact_paths,
)
manifest

{'experiment': 'lloom_v2.1_semantic_diagnostics',
 'corpus_id': 'nickbes/lawsofisrael',
 'n_bills': 100,
 'n_chunks': 100,
 'chat_model': 'gemini-3.5-flash-lite',
 'embed_model': 'bge-m3',
 'lloom_version': '0.8.2.1',
 'gen_params': {'filter_n_quotes': 5,
  'summ_n_bullets': 7,
  'synth_n_concepts': 3},
 'scored': False,
 'cluster_label_caveat': "Cluster labels describe a shared legal PATTERN (operative effect and explicit scope/conditions) across the enacted-law text of multiple bills. They do NOT establish shared legislative INTENT: final enacted-law text can support statements about legal effect and explicit scope, but cannot independently establish the government's unexpressed purpose. Trace each label to its exported source spans before drawing conclusions.",
 'timestamp': '2026-08-29T10:57:25.893939+00:00',
 'summarize_prompt_version': 'v2.1.2',
 'summarize_prompt_hash': 'e5d090a14eda',
 'synthesize_prompt_version': 'v2.0.0',
 'synthesize_prompt_hash': 'c141b3edbbe5',
 'bullet_accounting': {'n_input_chunks': 33,
  'n_chunks_with_bullets': 33,
  'n_chunks_without_bullets': 0,
  'n_bullets': 170,
  'chunk_ids_without_bullets': []},
 'nearest_neighbor': {'k': 5,
  'metric': 'cosine',
  'embed_backend': 'gemini:gemini-embedding-2-preview:dim=3072',
  'instruction': 'Represent this Israeli legislative rule for grouping by legal effect and subject-matter domain: ',
  'domain_context': True},
 'clustering': {'cluster_config': {'umap_n_neighbors': 15,
   'umap_n_components': 5,
   'umap_min_dist': 0.0,
   'umap_metric': 'cosine',
   'random_state': 42,
   'hdbscan_min_cluster_size': 4,
   'hdbscan_min_samples': None,
   'hdbscan_metric': 'euclidean',
   'hdbscan_cluster_selection_method': 'leaf',
   'hdbscan_cluster_selection_epsilon': 0.0,
   'config_version': 'v2.1.0'},
  'cluster_run_id': 'umap15x5_mcs4_leaf_seed42',
  'n_bullets': 170,
  'n_clusters': 21,
  'noise_ratio': 0.052941176470588235,
  'n_cross_bill_clusters': 8,
  'n_single_bill_clusters': 13,
  'bullet_prompt_hash': 'e5d090a14eda',
  'chosen_config_key': 'E'},
 'artifacts': {'bullets': 'notebooks/outputs/diagnostics/bullets_v2.parquet',
  'nearest_neighbors': 'notebooks/outputs/diagnostics/nearest_neighbors_v2.parquet',
  'condensed_tree': 'notebooks/outputs/diagnostics/condensed_tree_E_umap15x5_mcs4_leaf_seed42.parquet'}}

## 11. Export labels + provenance (for manual exploration)

If a configuration was chosen, write the label + provenance artifacts to
`notebooks/outputs/`. In the exploratory (no-config) state, **no labels are
written** — only the diagnostic artifacts from the sections above. There is
never a `scores.parquet`.

In [22]:
OUTPUTS.mkdir(parents=True, exist_ok=True)
(OUTPUTS / 'run_manifest_v2.json').write_text(
    json.dumps(manifest, ensure_ascii=False, indent=2), encoding='utf-8')

if not concepts_table:
    print("Exploratory state: no labels_v2.parquet / label_provenance_v2.parquet written.")
    print("Wrote diagnostics + run_manifest_v2.json only.")
    provenance_df = pd.DataFrame()
else:
    quotes_lookup, bullets_lookup = v2_export.distill_lookups(session)
    membership_table = v2_export.build_membership_table(
        session, chunk_lookup, quotes_lookup=quotes_lookup, bullets_lookup=bullets_lookup)
    v2_export.validate_provenance(concepts_table, membership_table)

    labels_df = pd.DataFrame(concepts_table)
    provenance_df = pd.DataFrame(membership_table)
    labels_df.to_parquet(OUTPUTS / 'labels_v2.parquet', index=False)
    provenance_df.to_parquet(OUTPUTS / 'label_provenance_v2.parquet', index=False)
    print(f"Exported labels_v2.parquet, label_provenance_v2.parquet, run_manifest_v2.json to {OUTPUTS}")

print(v2_export.CLUSTER_LABEL_CAVEAT)
provenance_df.head()

Exported labels_v2.parquet, label_provenance_v2.parquet, run_manifest_v2.json to /home/nick/Documents/projects/lawsofisrael/notebooks/outputs
Cluster labels describe a shared legal PATTERN (operative effect and explicit scope/conditions) across the enacted-law text of multiple bills. They do NOT establish shared legislative INTENT: final enacted-law text can support statements about legal effect and explicit scope, but cannot independently establish the government's unexpressed purpose. Trace each label to its exported source spans before drawing conclusions.

,concept_id,label,criterion,chunk_id,resolved,bill_id,bill_title,heading_path,page_no,source_spans,source_text,quotes,bullets
0,963593f4-0e3c-43db-9faf-497f22a7049b,"הארכת תוקף, תיקון או החלת הוראת שעה לגבי בתי ס...","האם הטקסט עוסק בהארכת תוקף, תיקון או קביעה של ...",1057303:0000,True,1057303,חוק לתיקון פקודת בתי הסוהר (הארכת הוראות שעה) ...,ספר החוקים,1,"[{'block_id': '1057303:b0001', 'heading_path':...","ט""ו באב התשפ""ו 3575 29 ביולי 2026\n\nעמוד\n\nח...",[חוק לתיקון פקודת בתי הסוהר )הארכת הוראות שעה(...,[הארכת הוראות השעה לתיקון פקודת בתי הסוהר בהתא...
1,963593f4-0e3c-43db-9faf-497f22a7049b,"הארכת תוקף, תיקון או החלת הוראת שעה לגבי בתי ס...","האם הטקסט עוסק בהארכת תוקף, תיקון או קביעה של ...",1057405:0000,True,1057405,חוק לתיקון ולהארכת תוקפן של תקנות שעת חירום (ח...,חוק לתיקון ולהארכת תוקפן של תקנות שעת חירום )ח...,2,"[{'block_id': '1057405:b0002', 'heading_path':...",. .1 בחוק לתיקון ולהארכת תוקפן של תקנות שעת חי...,[בחוק לתיקון ולהארכת תוקפן של תקנות שעת חירום ...,[תיקון חוק לתיקון ולהארכת תוקפן של תקנות שעת ח...
2,a4cbfc70-ad0e-409a-8de2-90fee4909ce5,תיקון חקיקה או הארכת תוקף הוראת שעה בענייני קט...,האם הטקסט עוסק בתיקון חוק או בהוראת שעה הנוגעת...,2229019:0000,True,2229019,חוק נוכחות עורך דין בחקירת קטינים ואנשים עם מו...,ספר החוקים,1,"[{'block_id': '2229019:b0001', 'heading_path':...","ט""ו באב התשפ""ו 3578 29 ביולי 2026\n\nעמוד\n\nס...",[תיקון חוק הליכי חקירה והעדה )התאמה לאנשים עם ...,[תיקון חוק הליכי חקירה והעדה מס' 5 לאנשים עם מ...
3,356272b8-d263-4fd1-ac82-73a628251be7,הארכת תוקף או תיקון הוראת שעה וסעיפים הנוגעים ...,"האם הטקסט עוסק בהארכת תוקף, תחולה או תיקון של ...",1057200:0000,True,1057200,חוק לתיקון פקודת סדר הדין הפלילי (מעצר וחיפוש)...,ספר החוקים,1,"[{'block_id': '1057200:b0001', 'heading_path':...","ו' באב התשפ""ו 3553 20 ביולי 2026\n\nעמוד\n\nחו...",[חוק לתיקון פקודת סדר הדין הפלילי )מעצר וחיפוש...,[התרת חיפוש ללא צו במקום או בבית בהתקיים חשד ס...
4,356272b8-d263-4fd1-ac82-73a628251be7,הארכת תוקף או תיקון הוראת שעה וסעיפים הנוגעים ...,"האם הטקסט עוסק בהארכת תוקף, תחולה או תיקון של ...",2220910:0000,True,2220910,"חוק שירות ביטחון (תיקון מס' 29 - הוראת שעה), ה...",,1,"[{'block_id': '2220910:b0000', 'heading_path':...","ספר החוקים\n\nה' באב התשפ""ו 3552 19 ביולי 2026...",[תיקון סעיף 15 -הוראת שעה\nיוצא צבא שהיה בשירו...,[תיקון סעיף 15 במסגרת הוראת שעה לגבי יוצא צבא ...

## 12. Trace a label: label → cluster → bullet neighbors → source chunk

For one selected label, walk the full evidence chain: the label, the chosen
clustering config it came from, the LLooM reasoning path (filter quotes + summary
bullets), the bullet's nearest neighbors, and the authoritative source text with
bill title/heading/page. This works only when a configuration was chosen.

In [23]:
if len(provenance_df):
    row = provenance_df.iloc[0]
    print("LABEL:    ", row['label'])
    print("CRITERION:", row['criterion'])
    print("CLUSTER:  ", chosen_result.config.run_id() if chosen_result else None)
    print("BILL:     ", row['bill_id'], '-', row['bill_title'])
    print("HEADING:  ", row['heading_path'], '| page', row['page_no'])

    print("\nFILTER QUOTES (LLooM-extracted):")
    for q in (row['quotes'] or []):
        print("  -", q)
    print("\nSUMMARY BULLETS (LLooM-generated):")
    for bl in (row['bullets'] or []):
        print("  -", bl)

    # Nearest neighbors of the chunk's first bullet, if present.
    first_bid = diag.bullet_row_id(row['chunk_id'], 0)
    nn = diag.neighbors_for(neighbor_rows, first_bid)
    if nn:
        print("\nNEAREST BULLET NEIGHBORS:")
        for r in nn:
            print(f"  [{r['rank']}] sim={r['similarity']:.3f}  {r['neighbor_bullet']}")

    print("\nSOURCE TEXT (authoritative, excerpt):")
    print((row['source_text'] or '')[:800])
else:
    print("No selected labels to trace (exploratory state or empty selection).")

LABEL:     הארכת תוקף, תיקון או החלת הוראת שעה לגבי בתי סוהר, עצורים ואסירים במצב חירום
CRITERION: האם הטקסט עוסק בהארכת תוקף, תיקון או קביעה של הוראת שעה הנוגעת לפקודת בתי הסוהר, לעצורים, לאסירים או לתנאי כליאה בשעת חירום?
CLUSTER:   umap15x5_mcs4_leaf_seed42
BILL:      1057303 - חוק לתיקון פקודת בתי הסוהר (הארכת הוראות שעה) (תיקוני חקיקה), התשפ"ו-2026
HEADING:   ספר החוקים | page 1

FILTER QUOTES (LLooM-extracted):
  - חוק לתיקון פקודת בתי הסוהר )הארכת הוראות שעה( )תיקוני חקיקה(, התשפ"ו2026
חוק לתיקון פקודת בתי הסוהר )מס' 64 - הוראת שעה - חרבות ברזל( )מצב חירום כליאתי(, התשפ"ד2023- - מס' 5
חוק לתיקון פקודת בתי הסוהר )תיקון מס' 66 - הוראת שעה - חרבות ברזל( )חופשה מיוחדת לאסיר(, התשפ"ד2024- - מס' 5
הוראת מעבר . .3 הכרזה שניתנה לפני תחילתו של חוק זה לפי סעיף 19כ לפקודה, כנוסחו בהוראת השעה האמורה בסעיף 1 לחוק זה, מוארכת ותמשיך לעמוד בתוקפה עד יום ד' בתשרי התשפ"ז )15 בספטמבר 2026( .
איתמר בן גביר השר לביטחון לאומי

SUMMARY BULLETS (LLooM-generated):
  - הארכת הוראות השעה לתיקון פקודת בתי הסוהר בהתאם לחוק התשפ"ו-2026
  - תיקון מספר 64 לפקודת בתי הסוהר במסגרת הוראת שעה למצב חירום כליאתי חרבות ברזל
  - תיקון מספר 66 לפקודת בתי הסוהר במסגרת הוראת שעה לחופשה מיוחדת לאסיר בחרבות ברזל
  - הארכת תוקף הכרזה שניתנה לפי סעיף 19כ לפקודת בתי הסוהר עד ליום ט"ו בספטמבר 2026

NEAREST BULLET NEIGHBORS:
  [1] sim=0.967  הארכת תוקף הכרזה שניתנה לפי סעיף 19כ לפקודת בתי הסוהר עד ליום ט"ו בספטמבר 2026
  [2] sim=0.961  תיקון מספר 64 לפקודת בתי הסוהר במסגרת הוראת שעה למצב חירום כליאתי חרבות ברזל
  [3] sim=0.946  תיקון מספר 66 לפקודת בתי הסוהר במסגרת הוראת שעה לחופשה מיוחדת לאסיר בחרבות ברזל
  [4] sim=0.906  הארכת תוקף תחולה והוראת שעה עד ליום 30 ביוני 2029 במקום 1 ביולי 2024
  [5] sim=0.901  תיקון חוק קיום דיונים בהיוועדות חזותית לעצורים אסירים וכלואים הוראת שעה

SOURCE TEXT (authoritative, excerpt):
ט"ו באב התשפ"ו 3575 29 ביולי 2026

עמוד

חוק לתיקון פקודת בתי הסוהר )הארכת הוראות שעה( )תיקוני חקיקה(, התשפ"ו20261048 תיקונים עקיפים: חוק לתיקון פקודת בתי הסוהר )מס' 64 - הוראת שעה - חרבות ברזל( )מצב חירום כליאתי(, התשפ"ד2023- - מס' 5 חוק לתיקון פקודת בתי הסוהר )תיקון מס' 66 - הוראת שעה - חרבות ברזל( )חופשה מיוחדת לאסיר(, התשפ"ד2024- - מס' 5

, בסעיף 1 -. .1 בחוק לתיקון פקודת בתי הסוהר )מס' 64 - הוראת שעה - חרבות ברזל( )מצב חירום 1 כליאתי(, התשפ"ד2023ד-

)1( ברישה, במקום "י"ז באב התשפ"ו )31 ביולי 2026(" יבוא "כ"ג בשבט התשפ"ז )31 בינואר2027(";

2 )להלן - הפקודה(, )2( בסעיף 19כ לפקודת בתי הסוהר ]נוסח חדש[, התשל"ב1971המובא בו -

)א( בסעיף קטן )א(, ברישה, במקום "המצב הביטחוני השורר במדינה, שבשלו ננקטו הפעולות הצבאיות המשמעותיות" יבוא "העלייה המשמעותית במספר האסירים שנובעת מהפעולות הצבאיות המשמ